define("entityshop/apply.js",["common/wx/Cgi.js","common/wx/Tips.js","common/wx/Step.js","common/wx/dialog.js","biz_web/ui/checkbox.js","biz_web/ui/dropdown.js","wxverify/validateExtend.js","biz_web/utils/upload.js","biz_common/jquery.validate.js","common/wx/qrcheck.js","common/wx/subjectAppealDialog.js","common/wx/inputCounter.js","entityshop/manage_category.js"],function(e){
"use strict";
function i(){
function e(){
console.log(x),x.isAgree&&x.qrcheck_ticket&&"1"==x.qrcheck_status?i.enable():i.disable();
}
u.setStep(1),x.qrcheck_ticket="",x.isAgree=!1,x.realnameTypeText={
0:"个人",
1:"企业",
2:"媒体",
3:"政府",
4:"其他组织",
5:"团队"
},o.html(a("tpl_step1",x));
var i=$("#js_btn_next"),l=$("#js_check_agree");
l.checkbox({
onChanged:function(){
x.isAgree=!x.isAgree,e();
}
}),i.on("click",function(){
return x.qrcheck_ticket&&x.isAgree&&!$(this).hasClass("btn_disabled")?void t():!1;
}),f=new y({
container:"#js_div_qrcheck",
container_class:"",
size:120,
idCard:x.cotractor_id,
name:x.cotractor_name,
extra:{
need_mask:1
},
renderData:{
name_title:"运营者"
},
scene:13,
askSpeed:5,
askMaxNum:60,
cgiURI:"/acct/slaveqrcheckoper",
onTicketChange:function(i){
console.log("ticket change:",i),x.qrcheck_ticket=i,e();
},
onStatusChange:function(i){
console.log("status change:",i),x.qrcheck_status=i,e();
},
onTipsChange:function(e,i){
console.log("onTipsChange",e,i);
var t=void 0;
return $("#tpl_qrcheck_ret_"+e).length>0&&(t=$("#tpl_qrcheck_ret_"+e).html()),t;
}
}),f.updateUser(null,null);
}
function t(){
function e(e,i){
var l=t.validate(),n={},r=t.find('input[name="'+e+'"],textarea[name="'+e+'"]');
r.length&&(n[e]=i,""!=i?(n[e]=i,setTimeout(function(){
l.showErrors(n);
},1)):r.valid());
}
u.setStep(2),o.html(a("tpl_step2",x));
var t=$("#js_form"),r=$("#js_btn_pre"),m=$("#js_btn_submit");
wx.cgiData.cat_infos&&(k=wx.cgiData.cat_infos||[]),console.log("categoryList:",k.length),
v.getCategoryListSync(k,function(){
console.log("cat ok");
new v.classFn({
type:"add",
qrcheckTicket:x.qrcheck_ticket,
curCategorList:[],
data:{},
previewImg:!0,
container:$("#js_div_category"),
canDel:!1,
limit:1,
ini_value_flag:!1
});
},function(){
console.log("cat fail");
}),new h('input[name="nickname"]',{
minLength:4,
maxLength:30,
showCounter:!0,
useGBKLength:!0
}),new h('textarea[name="intro"]',{
minLength:1,
maxLength:120,
showCounter:!0,
useGBKLength:!1
}),r.on("click",function(){
i();
}),m.on("click",function(){
return $(this).hasClass("btn_disabled")?!1:void t.submit();
}),l(),$('input[name="nickname"]').change(function(){
p=!1,$(".js_need_complete_material").hide();
}),t.find(".js_select_file").each(function(){
var e=$(this).attr("id"),i=c.uploadTmpFileWithCheck({});
!function(e){
i({
container:"#"+e,
multi:!1,
type:2,
accept:{
extensions:"bmp,jpeg,jpg,png",
mimeTypes:"image/*"
},
width:106,
onComplete:function(i,t,l,n){
var r=n.content||"",a=$("#"+e).parents(".frm_controls");
0==n.base_resp.ret?(a.find(".upload_preview").html('<img style="width:200px;" src="%s">'.sprintf(c.tmpFileUrl(r))).show(),
a.find('input[type="hidden"]').val(r),a.find(".fail").remove(),_.suc("上传成功")):_.err(200010==n.base_resp.ret?"图片太大":200011==n.base_resp.ret?"请上传合法的图片格式":200034==n.base_resp.ret?"图片尺寸错误":"上传失败");
}
});
}(e);
}),t.validate({
ignore:"",
rules:{
nickname:{
required:!0,
rangelen:[4,30]
},
intro:{
required:!0,
rangelength:[1,120]
},
headimg:{
required:!0
},
qualification_list_1:{
required:!0
},
first:{
required:!0
},
second:{
required:!0
}
},
messages:{
nickname:{
required:"请填写商家名称",
rangelength:$.validator.format("商家名称为{0}到{1}个中英文")
},
intro:{
required:"请填写商家介绍",
rangelength:$.validator.format("商家介绍为{0}到{1}个中英文")
},
headimg:{
required:"请上传头像"
},
qualification_list_1:{
required:"请上传经营资质"
},
first:{
required:"请选择类目"
},
second:{
required:"请选择类目"
}
},
errorPlacement:function(e,i){
var t=i.parent().parent(),l=t.find(".frm_tips");
t.find(".fail").remove(),l.length?e.insertBefore(l):t.append(e);
}
});
var p=!1,y=!1;
t.on("submit",function(){
if(!t.valid()||y)return!1;
var i={
nickname:$('input[name="nickname"]').val(),
headimg_mediaid:$('input[name="headimg"]').val(),
intro:$('textarea[name="intro"]').val(),
first_catid:$('input[name="first"]').val(),
second_catid:$('input[name="second"]').val(),
qualification_list:[],
qrcheck_ticket:x.qrcheck_ticket
};
if("undefined"==typeof i.first_catid||"undefined"==typeof i.second_catid)return _.err("请选择类目"),
!1;
if($(".js_credentials .js_upload_hidden").each(function(){
var e=$(this).val();
e&&(e=e.split(","),i.qualification_list.push(e[1]));
}),i.qualification_list=i.qualification_list.join("|"),!i.qualification_list&&$(".js_credentials .js_upload_hidden").length>0)return _.err("请上传资质文件"),
!1;
if(p){
var l=$("#idcardFile_hidden").val();
if(!l)return _.err("请上传营业执照或组织代码证"),!1;
var r=$("#othersFile_hidden").val();
i.org_code=l,i.other_files=r;
}
return console.log("postData:",i),m.btn(!1),y=!0,s.post({
url:"/merchant/newentityshop?action=apply_submit",
data:i,
complete:function(){
y=!1;
}
},function(t){
if(m.btn(!0),y=!1,!t||!t.base_resp)return void _.err("系统错误，请重试");
switch(t.base_resp.ret){
case 0:
n();
break;

case 10035:
e("nickname","你申请的名称需要补充相应资料进行审核"),p=!0,$(".js_need_complete_material").show(),$("#js_complement_wording").text(t.check_nickname_wording);
break;

case 4:
case 14:
_.err("管理员手机登记数量已超过上限，不能使用该主体开通门店");
break;

case 10022:
e("nickname","商家名称已被占用，请换一个重试。");
break;

case 10027:
_.err("该微信号已绑定5个管理员，请使用另一个微信号完成信息登记");
break;

case 10028:
_.err("管理员身份证已登记过5次，请使用另一个身份证完成用户信息登记");
break;

case 10029:
_.err("该主体登记数量已超过上限，不能使用该主体开通门店");
break;

case 10030:
_.err("管理员手机已经登记过5次，请使用另一个手机号进行用户信息登记");
break;

case 10031:
e("nickname","名称不能包含违反公众平台协议、相关法律法规和政策的内容，不得使用“微信”等保留字");
break;

case 10032:
e("intro","介绍中不得含有虚假的、冒充、利用他人名义的、容易构成混淆、误认的、法律、法规和政策禁止的内容。");
break;

case 10037:
e("nickname","该名称与已有公众号名称重复，需与该小程序帐号相同主体才可申请。");
break;

case 211003:
e("nickname","商家名称在改名2天保护期内，请换一个重试。");
break;

case 1004:
e("nickname","名称与已有帐号名称重复。请提交与订阅号、服务号、小程序不重复的帐号名称。");
break;

case 260003:
e("nickname","该名称与已有小程序名称重复，请重新提交一个新的名称，%s查看同名帐号%s。".sprintf("<a href='javascript:;' id='js_viewsameaccount'>","</a>")),
setTimeout(function(){
$("#js_viewsameaccount").click(function(){
window.open(wx.url("/acct/newinfringement?action=search_biz_list&search_type=1&complain_type=11&begin=0&nickname="+encodeURIComponent(i.nickname)));
});
},100);
break;

case 260007:
var l=i.nickname.replace("+","");
l==i.nickname&&(l+="+"),e("nickname","需与该帐号相同主体才可申请，%s查看同名帐号%s".sprintf("<a href='javascript:;' id='js_viewsameaccount'>","</a>")),
setTimeout(function(){
$("#js_viewsameaccount").click(function(){
window.open(wx.url("/acct/newinfringement?action=search_biz_list&search_type=1&complain_type=11&begin=0&nickname="+encodeURIComponent(l)));
});
},100);
break;

case 260008:
e("nickname","该名称与已有公众号名称重复，需与该小程序帐号相同主体才可申请，%s查看同名帐号%s。".sprintf("<a href='javascript:;' id='js_viewsameaccount'>","</a>")),
setTimeout(function(){
$("#js_viewsameaccount").click(function(){
window.open(wx.url("/acct/newinfringement?action=search_biz_list&search_type=1&complain_type=11&begin=0&nickname="+encodeURIComponent(i.nickname)));
});
},100);
break;

case 260009:
e("nickname","该名称与已有多个公众号名称重复，暂不支持申请，请重新提交一个新的名称，%s查看同名帐号%s。".sprintf("<a href='javascript:;' id='js_viewsameaccount'>","</a>")),
setTimeout(function(){
$("#js_viewsameaccount").click(function(){
window.open(wx.url("/acct/newinfringement?action=search_biz_list&search_type=1&complain_type=11&begin=0&nickname="+encodeURIComponent(i.nickname)));
});
},100);
break;

case 260010:
var l=i.nickname.replace("+","");
l==i.nickname&&(l+="+"),e("nickname","需与该帐号相同主体才可申请，%s查看同名帐号%s".sprintf("<a href='javascript:;' id='js_viewsameaccount'>","</a>")),
setTimeout(function(){
$("#js_viewsameaccount").click(function(){
window.open(wx.url("/acct/newinfringement?action=search_biz_list&search_type=1&complain_type=11&begin=0&nickname="+encodeURIComponent(l)));
});
},100);
break;

case 200013:
e("nickname","提交次数过于频繁，请稍后再试");
break;

case 210041:
e("nickname","名称长度为4-30个字符，不能含有特殊字符及“微信”等保留字");
break;

case 210050:
case 210044:
e("nickname","名称不能与已有公众帐号的微信号重复");
break;

case 210046:
e("nickname","该名称在侵权投诉保护期，暂不支持申请，请重新提交一个新的名称");
break;

case 65201:
e("nickname","不能使用该名称");
break;

case 211003:
e("nickname","名称正在2天保护期中，暂不能申请使用；你可在保护期满后重新申请使用该名称");
break;

case 10041:
_.err("公众号主体命中黑名单，不能开通门店");
break;

case 10042:
_.err("为保障平台安全，此帐号不能继续注册");
break;

case 10043:
_.err("为保障平台安全，此帐号不能继续注册");
break;

case 10044:
_.err("为保障平台安全，此帐号不能继续注册");
break;

case 10045:
_.err("操作过于频繁，请稍后再试");
break;

case 10046:
_.err("安全检查没有通过，不能开通门店");
break;

case 10047:
n();
break;

case 200700:
new d({
reason:t.reason,
canAppeal:!t.ban_appeal,
jumpUrl:wx.url("/cgi-bin/contractorappeal?action=index"),
appealTicket:t.appeal_ticket
});
break;

default:
_.err("系统错误，请重试");
}
}),!1;
});
}
function l(e){
function i(e,i,t,l,n){
var r='<div class="upload_preview_item"> 	                <span class="file_title">%s</span> 	                <a class="file_opr" target="_blank" href="%s">查看</a> 	                <a class="file_opr js_delete_preview_file" data-key="%s" href="javascript:void(0);">删除</a> 	            </div>")';
if("bizmedia"==l)var a=wx.url("/merchant/newentityshop?action=getstoreimg&id="+e);else if("preview"==l)var a=c.tmpFileUrl(e);else if("multimedia"==l)var a=c.multimediaFileUrl(e);
return r.sprintf(n?n:"材料"+(i+1)+".png",a,t);
}
$(".js_select_file_comp").each(function(){
var t=$(this),l=t.attr("id"),n=l,r=t.attr("data-max")||1,a=t.attr("data-type")||2;
b[n]||(b[n]=[]);
var s=b[n];
!function(t,l,n,a){
q[t]=a.length,c.uploadTmpFile({
container:"#"+t,
multi:r>1?!0:!1,
type:l,
onSelect:function(){
return 1!=r?q[t]>=r?(_.err("最多上传%s个材料".sprintf(r)),!1):void(q[t]=q[t]+1):void 0;
},
onError:function(){
q[t]=q[t]-1;
},
onCancel:function(){
q[t]=q[t]-1;
},
onComplete:function(l,s,m,p){
var y=p.content||"";
if(0==p.base_resp.ret){
var d=$("#"+t+"_preview");
1>=r?(a=[y],d.html('<img src="%s" style="width:200px;">'.sprintf(c.tmpFileUrl(y)))):(a.push(y),
d.append(i(y,a.length,n,"preview",m.name))),d.parent().find(".fail").remove(),$("#"+t+"_hidden").val(a.join("|")),
e&&e(y),_.suc("上传成功");
}
}
});
}(l,a,n,s);
});
}
function n(){
o.html(a("tpl_result",x)),$("#js_div_step").hide();
}
function r(){
o=$("#js_container"),u=new m({
container:"#js_div_step",
selected:1,
names:["确认商家资质","填写商家信息"]
}),1==wx.cgiData.is_overseas?o.html(a("tpl_no_overseas")):i();
}
var a=template.render,s=e("common/wx/Cgi.js"),_=e("common/wx/Tips.js"),m=e("common/wx/Step.js"),p=e("common/wx/dialog.js"),c=(e("biz_web/ui/checkbox.js"),
e("biz_web/ui/dropdown.js"),e("wxverify/validateExtend.js"),e("biz_web/utils/upload.js")),y=(e("biz_common/jquery.validate.js"),
e("common/wx/qrcheck.js")),d=e("common/wx/subjectAppealDialog.js"),h=e("common/wx/inputCounter.js"),v=e("entityshop/manage_category.js"),f=null,u=null,x=wx.cgiData,o=null,q={},b={};
$("#js_container").on("click",".js_delete_preview_file",function(){
var e=$(this).attr("data-key"),i=parseInt($(this).attr("data-idx"));
$(this).parent().remove();
var t=b[e];
t.splice(i,1),$("#"+e+"_hidden").val(t.join("|")),q[e]=q[e]-1;
});
var k=[{
children:[1,8,42,52,99,110,135,150,210,220,231,684,275,287,304,402,407,674,780,868],
id:0,
type_list:[0,1,2,3,4,5]
},{
children:[2,5,556,558],
father:0,
id:1,
level:1,
name:"快递业与邮政",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[9,590,592,27,32,37,39,578,580,582],
father:0,
id:8,
level:1,
name:"教育",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[43,47,50,400,411,560,562,564,864],
father:0,
id:42,
level:1,
name:"医疗",
sensitive_type:0,
type_list:[1,2,3,4]
},{
children:[53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,409,700,702,704,706,708,710,712,714,716,718,720,722,724,726,728,730,732,734,736,738,740,742,744,746,748,750,752,754,756,758,760,762,764,766,768,770,772],
father:0,
id:52,
level:1,
name:"政务民生",
sensitive_type:0,
type_list:[1,2,3,4]
},{
children:[100,102,104,106,108,401,410,412,568,802],
father:0,
id:99,
level:1,
name:"金融业",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[1,2,3,4,0]
},{
children:[111,116,119,121,123,125,127,129,131,133,648,650,652,654,656,658],
father:0,
id:110,
level:1,
name:"出行与交通",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[146,138,140,142],
father:0,
id:135,
level:1,
name:"房地产",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[151,155,157,173,185,196,198,200,202,672,208,664,666,668,670,866],
father:0,
id:150,
level:1,
name:"生活服务",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[211,213,413],
father:0,
id:210,
level:1,
name:"IT科技",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[221,225,638,632,634,636],
father:0,
id:220,
level:1,
name:"餐饮",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[232,235,238,240,242,640,642,644],
father:0,
id:231,
level:1,
name:"旅游",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[790,792,794,796,798,800,872],
father:0,
id:684,
level:1,
name:"社交",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[276,279,281,283,285,594,600,602,604,606],
father:0,
id:275,
level:1,
name:"文娱",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[288,290,292,294,296,298,300,302,608,610,612,614,616,618,620,698],
father:0,
id:287,
level:1,
name:"工具",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[305,307,309,311,313,315,317,319,321,323,325,327,329,331,552,554,784,786,788,816,818],
father:0,
id:304,
level:1,
name:"商家自营",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[1,2,3,4,0]
},{
children:[403,404,405,406,628,774,776,778,810,812,870,876,878,880],
father:0,
id:402,
level:1,
name:"商业服务",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[408,630],
father:0,
id:407,
level:1,
name:"公益",
sensitive_type:0,
type_list:[1,2,3,4]
},{
children:[676,678,680,682],
father:0,
id:674,
level:1,
name:"体育",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,4,3]
},{
children:[782],
father:0,
id:780,
level:1,
name:"电商平台",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[1,2,3,4]
},{
children:[874],
father:0,
id:868,
level:1,
name:"时政信息",
qualify:{
exter_list:[{
inner_list:[{
name:"有资质证件：《互联网新闻信息服务许可证》",
url:""
}]
},{
inner_list:[{
name:"无资质：ICP备案",
url:""
}]
}],
remark:"有资质则提供：《互联网新闻信息服务许可证》，无资质则提供ICP备案"
},
sensitive_type:1,
type_list:[1,2,3,4,0]
},{
children:[3,4],
father:1,
id:2,
level:2,
name:"快递、物流",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[6,7],
father:1,
id:5,
level:2,
name:"仓储",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:1,
id:556,
level:2,
name:"邮政",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,4,3]
},{
children:[],
father:1,
id:558,
level:2,
name:"装卸搬运",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[588,586,584],
father:8,
id:9,
level:2,
name:"学历教育",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:8,
id:590,
level:2,
name:"出国留学",
qualify:{
exter_list:[{
inner_list:[{
name:"《自费出国留学中介服务机构资格认定书》",
url:""
}]
}],
remark:"《自费出国留学中介服务机构资格认定书》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:8,
id:592,
level:2,
name:"教育装备",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[28,29,30,31],
father:8,
id:27,
level:2,
name:"婴幼儿教育",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:8,
id:32,
level:2,
name:"在线教育",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[38,570,572,574,576],
father:8,
id:37,
level:2,
name:"培训机构",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:8,
id:39,
level:2,
name:"出国移民",
qualify:{
exter_list:[{
inner_list:[{
name:"非广东省：《因私出入境中介机构经营许可证》",
url:""
}]
},{
inner_list:[{
name:"广东省：提供营业执照",
url:""
}]
}],
remark:"如果提供的是营业执照，检查是不是广东省的且经营范围含有提供出国探亲访友等信息咨询服务。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:8,
id:578,
level:2,
name:"教育信息服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:8,
id:580,
level:2,
name:"驾校培训",
qualify:{
exter_list:[{
inner_list:[{
name:"需提供《道路运输经营许可证》，且其中须有“驾驶员培训”项目",
url:""
}]
}],
remark:"需提供《道路运输经营许可证》，且其中须有“驾驶员培训”项目"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:8,
id:582,
level:2,
name:"特殊人群教育",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[44,45,46],
father:42,
id:43,
level:2,
name:"就医服务",
qualify:{
exter_list:[{
inner_list:[{
name:"卫生和计划生育委员会批文",
url:""
}]
},{
inner_list:[{
name:"提交签订协议的医院列表+其中一份协议+承诺书，且将全部协议文件发送至邮箱weixin_developer@qq.com",
url:""
}]
}],
remark:"卫生和计划生育委员会批文或者签订协议的医院列表、其中一份协议、承诺书，且将全部协议文件发送至邮箱weixin_developer@qq.com"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:42,
id:47,
level:2,
name:"私立医疗机构",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKv0GmicCRECkR8ngEG4piap4TeWnj3Ro0CY1PIDlI4s9TEt0AlNVwEnIA/0?wx_fmt=png"
},{
name:"《医疗机构执业许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKX7a1lpia3zvIFEZNDf5Q5GiaI2Tr0kA8GqZG25SMFOBQQ0icoZ04nzjWA/0?wx_fmt=png"
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》"
},{
name:"《医疗机构执业许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKX7a1lpia3zvIFEZNDf5Q5GiaI2Tr0kA8GqZG25SMFOBQQ0icoZ04nzjWA/0?wx_fmt=png"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[51],
father:42,
id:50,
level:2,
name:"药品信息展示",
qualify:{
exter_list:[{
inner_list:[{
name:"《互联网药品信息服务资格证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKibaZZ4Mqy4YAF2kDFPCefmv7cNylZNia6Ub89iaGQXbeQVpchY1PWL6BA/0?wx_fmt=png"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:42,
id:400,
level:2,
name:"医疗保健信息服务",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKv0GmicCRECkR8ngEG4piap4TeWnj3Ro0CY1PIDlI4s9TEt0AlNVwEnIA/0?wx_fmt=png"
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
}]
}],
remark:"1：服务项目类别中需包含“互联网医疗保健信息服务” 2：2015年10月11日取消《互联网医疗保健信息服务审核同意书》。若2015年的，可以提供《互联网医疗保健信息服务审核同意书》，只要在有限期内。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:42,
id:411,
level:2,
name:"公立医疗机构",
qualify:{
exter_list:[{
inner_list:[{
name:"《医疗机构执业许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKX7a1lpia3zvIFEZNDf5Q5GiaI2Tr0kA8GqZG25SMFOBQQ0icoZ04nzjWA/0?wx_fmt=png"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:42,
id:560,
level:2,
name:"医疗器械信息展示",
qualify:{
exter_list:[{
inner_list:[{
name:"《互联网药品信息服务资格证》",
url:""
}]
}],
remark:"《互联网药品信息服务资格证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:42,
id:562,
level:2,
name:"医疗器械生产企业",
qualify:{
exter_list:[{
inner_list:[{
name:"《医疗器械生产许可证》",
url:""
}]
}],
remark:"《医疗器械生产许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:42,
id:564,
level:2,
name:"医疗器械经营、销售",
qualify:{
exter_list:[{
inner_list:[{
name:"《医疗器械经营许可证》",
url:""
}]
}],
remark:"医疗器械经营监督管理办法 中规定对于第二类医疗器械，采用备案方式。如果该小程序涉及医疗器械展示，同时要求提供：互联网药品信息服务资格证。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:42,
id:864,
level:2,
name:"互联网医院",
qualify:{
exter_list:[{
inner_list:[{
name:"《卫计委批文》",
url:""
},{
name:"《ICP备案》",
url:""
},{
name:"《合作医院的医疗机构执业许可证》",
url:""
}]
}],
remark:"《卫计委批文》+《ICP备案》+《合作医院的医疗机构执业许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[54],
father:52,
id:53,
level:2,
name:"交通违法",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
},{
name:"《增值电信业务经营许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKv0GmicCRECkR8ngEG4piap4TeWnj3Ro0CY1PIDlI4s9TEt0AlNVwEnIA/0?wx_fmt=png"
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[56],
father:52,
id:55,
level:2,
name:"博物馆",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[58],
father:52,
id:57,
level:2,
name:"出入境",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[60],
father:52,
id:59,
level:2,
name:"邮政",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[62],
father:52,
id:61,
level:2,
name:"车管所服务",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[64],
father:52,
id:63,
level:2,
name:"城市道路",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[66],
father:52,
id:65,
level:2,
name:"高速服务",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[68],
father:52,
id:67,
level:2,
name:"税务",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[70],
father:52,
id:69,
level:2,
name:"司法",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[72],
father:52,
id:71,
level:2,
name:"消防",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[74],
father:52,
id:73,
level:2,
name:"气象",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[76],
father:52,
id:75,
level:2,
name:"户政",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[78],
father:52,
id:77,
level:2,
name:"治安",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[80],
father:52,
id:79,
level:2,
name:"环保",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[82],
father:52,
id:81,
level:2,
name:"民政",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[86],
father:52,
id:85,
level:2,
name:"教育",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[88],
father:52,
id:87,
level:2,
name:"水电局",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[90],
father:52,
id:89,
level:2,
name:"工商",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[92],
father:52,
id:91,
level:2,
name:"住建",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[94],
father:52,
id:93,
level:2,
name:"人力资源",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[96],
father:52,
id:95,
level:2,
name:"文化",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[98],
father:52,
id:97,
level:2,
name:"社会保障",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:409,
level:2,
name:"图书馆",
qualify:{
exter_list:[{
inner_list:[{
name:"《相关政府部门的资质授权文件》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyu9SrVj98VicABVSpILdxrqXemQQb9ZYHBMRibhicatKiaeW2XIWhcGksA/0?wx_fmt=jpeg"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:700,
level:2,
name:"交警",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:702,
level:2,
name:"边防",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:704,
level:2,
name:"国安",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:706,
level:2,
name:"公证",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:708,
level:2,
name:"检察院",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:710,
level:2,
name:"法院",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:712,
level:2,
name:"纪检审计",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:714,
level:2,
name:"财政",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:716,
level:2,
name:"公积金",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:718,
level:2,
name:"党团组织",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:720,
level:2,
name:"安监",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:722,
level:2,
name:"医疗",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:724,
level:2,
name:"计划生育",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:726,
level:2,
name:"体育",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:728,
level:2,
name:"水利",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:730,
level:2,
name:"食药监",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:732,
level:2,
name:"质监",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:734,
level:2,
name:"新闻出版及广电",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:736,
level:2,
name:"知识产权",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:738,
level:2,
name:"旅游局",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:740,
level:2,
name:"信访",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:742,
level:2,
name:"物价粮食",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:744,
level:2,
name:"城管",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:746,
level:2,
name:"监狱戒毒",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:748,
level:2,
name:"海关",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:750,
level:2,
name:"检验检疫",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:752,
level:2,
name:"交通",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:754,
level:2,
name:"商务",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:756,
level:2,
name:"航空",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:758,
level:2,
name:"街道居委",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:760,
level:2,
name:"农林畜牧海洋",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:762,
level:2,
name:"社科档案",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:764,
level:2,
name:"政府应急办",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:766,
level:2,
name:"科学技术与地质",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:768,
level:2,
name:"统计",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:770,
level:2,
name:"经济发展与改革",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:52,
id:772,
level:2,
name:"政务服务大厅",
qualify:{
exter_list:[{
inner_list:[{
name:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。",
url:""
}]
}],
remark:"认证主体需为业务对应政府或事业单位。如非对应单位，需提供对应单位授权或合作协议。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:99,
id:100,
level:2,
name:"基金",
qualify:{
exter_list:[{
inner_list:[{
name:"《经营证券期货业务许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyS0FcyUIiaKofUZI8Hia3YFUZVSc4OwqDXvUtKlKj8TKqcCP6otG6rOw/0?wx_fmt=png"
}]
},{
inner_list:[{
name:"《基金托管业务许可证》",
url:""
}]
},{
inner_list:[{
name:"《基金销售业务资格证书》",
url:""
}]
}],
remark:"1：《经营证券期货业务许可证》且业务范围必须包含“基金”或《基金托管业务许可证》或《基金销售业务资格证书》2：有效期内的《基金管理资格证书》可以代替《经营期货业务许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4,0]
},{
children:[],
father:99,
id:102,
level:2,
name:"信托",
qualify:{
exter_list:[{
inner_list:[{
name:"《金融许可证》"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:99,
id:104,
level:2,
name:"网络借贷信息中介（P2P）",
qualify:{
exter_list:[{
inner_list:[{
name:"银监会备案证明材料",
url:""
}]
},{
inner_list:[{
name:"省（自治区、直辖市）金融办批准文件",
url:""
}]
}],
remark:"银监会备案证明材料或者省（自治区、直辖市）金融办批准文件"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:99,
id:106,
level:2,
name:"保险",
qualify:{
exter_list:[{
inner_list:[{
name:"《保险公司法人许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/iaP1bic8gWpSYCBPiaPOdmASkYrrVIgDUgeEic1V2pAdEGJxHzZ2uAztSeZAkwnMRy5zNicFFybtV65DOb0EcMGyq6w/0?wx_fmt=jpeg"
}]
},{
inner_list:[{
name:"《经营保险业务许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QK6CsK98lldic2ehhJYZhhiaKZAYoUtkJXzBddyfsAic0nbr6LofTkzkWIg/0?wx_fmt=png"
}]
}],
remark:"其中 经营保险业务许可证中，可以为以下其一：1：保险营销服务许可证；2：经营保险代理业务许可证；3：经营保险经纪业务许可证；4：经营保险公估业务许可证；5：保险兼业代理业务许可证；6：保险资产管理公司法人许可证和经营保险资产管理业务许可证。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[109],
father:99,
id:108,
level:2,
name:"银行",
qualify:{
exter_list:[{
inner_list:[{
name:"《金融机构许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKjjOUg4gCWkuCGlFjekfV3951vfRr6IBLBmFwVk9OsHjpopcuWUL9rQ/0?wx_fmt=png"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:99,
id:401,
level:2,
name:"股票信息服务平台",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKv0GmicCRECkR8ngEG4piap4TeWnj3Ro0CY1PIDlI4s9TEt0AlNVwEnIA/0?wx_fmt=png"
},{
name:"《深圳交易所专有信息经营许可合同》",
url:""
},{
name:"《上证所证券信息经营许可合同》",
url:""
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
},{
name:"《深圳交易所专有信息经营许可合同》",
url:""
},{
name:"《上证所证券信息经营许可合同》",
url:""
}]
}],
remark:"《增值电信业务经营许可证》且核准服务项目包含“财经投资类互联网电子公告服务”"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:99,
id:410,
level:2,
name:"证券/期货",
qualify:{
exter_list:[{
inner_list:[{
name:"《经营证券期货业务许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKyS0FcyUIiaKofUZI8Hia3YFUZVSc4OwqDXvUtKlKj8TKqcCP6otG6rOw/0?wx_fmt=png"
}]
}],
remark:"《经营证券业务许可证》也可以，但必须在有效期内。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:99,
id:412,
level:2,
name:"证券/期货投资咨询",
qualify:{
exter_list:[{
inner_list:[{
name:"《证券投资咨询业务资格证书》"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:99,
id:568,
level:2,
name:"非金融机构自营小额贷款",
qualify:{
exter_list:[{
inner_list:[{
name:"《省金融办批准文件》",
url:""
}]
}],
remark:"省金融办批准文件"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:99,
id:802,
level:2,
name:"新三板信息服务平台",
qualify:{
exter_list:[{
inner_list:[{
name:"全国中小企业股份转让系统有限责任公司的书面许可",
url:""
},{
name:"ICP备案",
url:""
}]
}],
remark:"全国中小企业股份转让系统有限责任公司的书面许可+ICP备"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[112,113,114,115,646],
father:110,
id:111,
level:2,
name:"打车",
qualify:{
exter_list:[{
inner_list:[{
name:"《网络预约出租汽车经营许可证》",
url:""
}]
}],
remark:"《网络预约出租汽车经营许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[117,118,806,808],
father:110,
id:116,
level:2,
name:"航空",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[1,2,3,4,0]
},{
children:[120],
father:110,
id:119,
level:2,
name:"火车",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[122,566],
father:110,
id:121,
level:2,
name:"公交",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:110,
id:123,
level:2,
name:"长途客运",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[126],
father:110,
id:125,
level:2,
name:"停车",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[128],
father:110,
id:127,
level:2,
name:"代驾",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[130],
father:110,
id:129,
level:2,
name:"租车",
qualify:{
exter_list:[{
inner_list:[{
name:"《汽车租赁经营许可证》"
}]
}]
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[132],
father:110,
id:131,
level:2,
name:"路况",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[134],
father:110,
id:133,
level:2,
name:"水运",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:110,
id:648,
level:2,
name:"地铁",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:110,
id:650,
level:2,
name:"路桥收费",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:110,
id:652,
level:2,
name:"加油/充电桩",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:110,
id:654,
level:2,
name:"城市交通卡",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:110,
id:656,
level:2,
name:"城市共享交通",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:110,
id:658,
level:2,
name:"高速服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[147],
father:135,
id:146,
level:2,
name:"装修/建材",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[139],
father:135,
id:138,
level:2,
name:"物业管理",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[141],
father:135,
id:140,
level:2,
name:"房地产开发经营",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[143,144,145],
father:135,
id:142,
level:2,
name:"房产交易",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[152,153,154,662],
father:150,
id:151,
level:2,
name:"票务",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[156],
father:150,
id:155,
level:2,
name:"生活缴费",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:150,
id:157,
level:2,
name:"家政",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:150,
id:173,
level:2,
name:"外送",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[814,820,822,824,826,828,830,832,834,836,838],
father:150,
id:185,
level:2,
name:"丽人",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[197],
father:150,
id:196,
level:2,
name:"宠物（非医院类）",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[199],
father:150,
id:198,
level:2,
name:"环保回收/废品回收",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[201],
father:150,
id:200,
level:2,
name:"摄影/扩印",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[203,204,205,660],
father:150,
id:202,
level:2,
name:"婚庆服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:150,
id:672,
level:2,
name:"洗浴保健",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[209],
father:150,
id:208,
level:2,
name:"养车/修车",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:150,
id:664,
level:2,
name:"综合生活服务平台",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:150,
id:666,
level:2,
name:"休闲娱乐",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:150,
id:668,
level:2,
name:"搬家公司",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:150,
id:670,
level:2,
name:"线下超市/便利店",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:150,
id:866,
level:2,
name:"宠物医院",
qualify:{
exter_list:[{
inner_list:[{
name:"《动物诊疗许可证》",
url:""
},{
name:"《动物防疫许可证》",
url:""
}]
}],
remark:"《动物诊疗许可证》+《动物防疫许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[212],
father:210,
id:211,
level:2,
name:"硬件与设备",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[214],
father:210,
id:213,
level:2,
name:"通信与运营商",
qualify:{
exter_list:[{
inner_list:[{
name:"《基础电信业务经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:""
}]
}],
remark:"《基础电信业务经营许可证》或者《增值电信业务经营许可证》"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:210,
id:413,
level:2,
name:"软件服务提供商",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKv0GmicCRECkR8ngEG4piap4TeWnj3Ro0CY1PIDlI4s9TEt0AlNVwEnIA/0?wx_fmt=png"
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》"
}]
}]
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:220,
id:221,
level:2,
name:"点评与推荐",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:220,
id:225,
level:2,
name:"菜谱",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:220,
id:638,
level:2,
name:"外卖",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[840,842,844,846,848,850,852,854,856,858,860,862],
father:220,
id:632,
level:2,
name:"门店",
qualify:{
exter_list:[{
inner_list:[{
name:"《食品经营许可证》",
url:""
}]
}],
remark:"《食品经营许可证》或有效期内餐饮服务场所公共场所的《卫生许可证》"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:220,
id:634,
level:2,
name:"餐厅排队",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,3,2,4]
},{
children:[],
father:220,
id:636,
level:2,
name:"点餐",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[233,234],
father:231,
id:232,
level:2,
name:"旅游线路",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[236,237],
father:231,
id:235,
level:2,
name:"酒店服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[239],
father:231,
id:238,
level:2,
name:"公寓/民宿",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[241],
father:231,
id:240,
level:2,
name:"门票",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[243],
father:231,
id:242,
level:2,
name:"出境WiFi",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:231,
id:640,
level:2,
name:"旅游攻略",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:231,
id:642,
level:2,
name:"签证",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:231,
id:644,
level:2,
name:"景区服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:684,
id:790,
level:2,
name:"陌生人交友",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
}]
}],
remark:"《增值电信业务经营许可证》或《电信与信息服务业务经营许可证》"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:684,
id:792,
level:2,
name:"熟人交友",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
}]
}],
remark:"《增值电信业务经营许可证》或《电信与信息服务业务经营许可证》"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:684,
id:794,
level:2,
name:"社区/论坛",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
}]
}],
remark:"《增值电信业务经营许可证》或《电信与信息服务业务经营许可证》"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:684,
id:796,
level:2,
name:"直播",
qualify:{
exter_list:[{
inner_list:[{
name:"《信息网络传播视听节目许可证》",
url:""
},{
name:"《网络文化经营许可证》（经营范围含网络表演）",
url:""
}]
}],
remark:"《信息网络传播视听节目许可证》和《网络文化经营许可证》（经营范围含网络表演）"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:684,
id:798,
level:2,
name:"婚恋",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证",
url:""
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
}]
}],
remark:"《增值电信业务经营许可证》或《电信与信息服务业务经营许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:684,
id:800,
level:2,
name:"问答",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
}]
}],
remark:"《增值电信业务经营许可证》或《电信与信息服务业务经营许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:684,
id:872,
level:2,
name:"笔记",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
}]
}],
remark:"《增值电信业务经营许可证》或《电信与信息服务业务经营许可证》"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:275,
id:276,
level:2,
name:"资讯",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[280],
father:275,
id:279,
level:2,
name:"视频",
qualify:{
exter_list:[{
inner_list:[{
name:"《信息网络传播视听节目许可证》",
url:""
}]
},{
inner_list:[{
name:"《广播电视节目制作经营许可证》",
url:""
}]
}],
remark:"《信息网络传播视听节目许可证》或 《广播电视节目制作经营许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[284],
father:275,
id:283,
level:2,
name:"音乐",
qualify:{
exter_list:[{
inner_list:[{
name:"《网络文化经营许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKFd6PJN29XZXYOtYWcYpuPRp6Z8GV15I2bIPC1qVjtnZde1P7AqnEmg/0?wx_fmt=png"
}]
},{
inner_list:[{
name:"《信息网络传播视听节目许可证》",
url:""
}]
}],
remark:"《网络文化经营许可证》或《信息网络传播视听节目许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[596,598],
father:275,
id:594,
level:2,
name:"小说",
qualify:{
exter_list:[{
inner_list:[{
name:"《互联网出版许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_jpg/EoS2aRYcKicJiaVUgCEdGKp0lv5vky5GT7OSTDu9bJ0ricBIgXNrWVxdblIRoJpUWRpxp72miaibUibuBqkhUeVpVkJw/0?wx_fmt=jpeg"
}]
},{
inner_list:[{
name:"《网络出版服务许可证》",
url:""
}]
}],
remark:"1：《互联网出版许可证》或者《网络出版服务许可证》 2：网络出版服务单位不得转借、出租、出卖《网络出版服务许可证》或以任何形式转让网络出版服务许可。也不得允许其他网络信息服务提供者以其名义提供网络出版服务，属于前款所称禁止行为。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:275,
id:602,
level:2,
name:"FM/电台",
qualify:{
exter_list:[{
inner_list:[{
name:"《信息网络传播视听节目许可证》",
url:""
}]
},{
inner_list:[{
name:"《广播电视节目制作经营许可证》",
url:""
}]
}],
remark:"《信息网络传播视听节目许可证》或 《广播电视节目制作经营许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:275,
id:604,
level:2,
name:"有声读物",
qualify:{
exter_list:[{
inner_list:[{
name:"《网络文化经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《信息网络传播视听节目许可证》",
url:""
}]
}],
remark:"《网络文化经营许可证》或《信息网络传播视听节目许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:275,
id:606,
level:2,
name:"动漫",
qualify:{
exter_list:[{
inner_list:[{
name:"《互联网出版许可证》",
url:""
},{
name:"《网络文化经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《网络出版服务许可证》",
url:""
},{
name:"《网络文化经营许可证》",
url:""
}]
}],
remark:"1：《互联网出版许可证》或者《网络出版服务许可证》和《网络文化经营许可证》 2：网络出版服务单位不得转借、出租、出卖《网络出版服务许可证》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[289],
father:287,
id:288,
level:2,
name:"记账",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[291],
father:287,
id:290,
level:2,
name:"投票",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[293],
father:287,
id:292,
level:2,
name:"日历",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[295],
father:287,
id:294,
level:2,
name:"天气",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[297],
father:287,
id:296,
level:2,
name:"备忘录",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[299],
father:287,
id:298,
level:2,
name:"办公",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[301],
father:287,
id:300,
level:2,
name:"字典",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[303],
father:287,
id:302,
level:2,
name:"图片/音频/视频",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:287,
id:608,
level:2,
name:"计算类",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:287,
id:610,
level:2,
name:"报价/比价",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:287,
id:612,
level:2,
name:"信息查询",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:287,
id:614,
level:2,
name:"网络代理",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:287,
id:616,
level:2,
name:"效率",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:287,
id:618,
level:2,
name:"健康管理",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:287,
id:620,
level:2,
name:"企业管理",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:287,
id:698,
level:2,
name:"预约/报名",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[308],
father:304,
id:307,
level:2,
name:"服装/鞋/箱包",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[310],
father:304,
id:309,
level:2,
name:"玩具/母婴用品(不含食品)",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[312],
father:304,
id:311,
level:2,
name:"家电/数码/手机",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[314],
father:304,
id:313,
level:2,
name:"保健品",
qualify:{
exter_list:[{
inner_list:[{
name:"《国产保健食品批准证书》",
url:""
}]
},{
inner_list:[{
name:"《进口保健食品批准证书》",
url:""
}]
}],
remark:"《国产保健食品批准证书》或《进口保健食品批准证书》，涉及进口需同时核查进口报关单及检验检疫卫生证书"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[316],
father:304,
id:315,
level:2,
name:"珠宝/饰品/眼镜/钟表",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[318],
father:304,
id:317,
level:2,
name:"运动/户外/乐器",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[320],
father:304,
id:319,
level:2,
name:"图书报刊/音像/影视/游戏/动漫",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[322],
father:304,
id:321,
level:2,
name:"食品/饮料/生鲜",
qualify:{
exter_list:[{
inner_list:[{
name:"《食品经营许可证》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKlUNzWSrsU7GLlpO4LgJWkicjM5ic1NR1eicKaHA4MToap61iaDQCYuibXTg/0?wx_fmt=png"
}]
}],
remark:"《食品流通许可证》在有效期内也可以"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[324],
father:304,
id:323,
level:2,
name:"鲜花/园艺/工艺品",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[326],
father:304,
id:325,
level:2,
name:"家居/家饰/家纺",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[328],
father:304,
id:327,
level:2,
name:"汽车/其他交通工具及配件",
qualify:{
exter_list:[{
inner_list:[{
name:"汽车供应商/生产企业授权",
url:""
}]
}],
remark:"4S店： 汽车供应商/生产企业授权；和 核查营业执照中经营范围是否包含“品牌汽车销售”  其他目录：涉及汽车关键零部件的，审核强制性产品认证证书（3C认证）"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[330],
father:304,
id:329,
level:2,
name:"办公/文具",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[332],
father:304,
id:331,
level:2,
name:"五金/建材/化工/矿产品",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:304,
id:552,
level:2,
name:"百货",
qualify:{
exter_list:[{
inner_list:[{
name:"《食品经营许可证》",
url:""
},{
name:"《酒类零售许可证》",
url:""
},{
name:"《食盐零售许可证》",
url:""
}]
}],
remark:"《食品经营许可证》和《酒类零售许可证》和《食盐零售许可证》"
},
sensitive_type:1,
type_list:[6,1,2,3,4]
},{
children:[],
father:304,
id:554,
level:2,
name:"宠物/农资",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[6,0,1,2,3,4]
},{
children:[],
father:304,
id:784,
level:2,
name:"海淘",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:304,
id:786,
level:2,
name:"美妆/洗护",
qualify:{
exter_list:[{
inner_list:[{
name:"《化妆品生产许可证》",
url:""
}]
},{
inner_list:[{
name:"《委托加工协议》",
url:""
}]
}],
remark:"《化妆品生产许可证》或《委托加工协议》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:304,
id:788,
level:2,
name:"机械/电子器件",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:304,
id:816,
level:2,
name:"成人用品",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[1,2,3,4,0]
},{
children:[],
father:304,
id:818,
level:2,
name:"酒/盐",
qualify:{
exter_list:[{
inner_list:[{
name:"《酒类零售许可证》",
url:""
}]
},{
inner_list:[{
name:"《食盐零售许可证》",
url:""
}]
}],
remark:"《酒类零售许可证》或《食盐零售许可证》"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[622,624,626],
father:402,
id:403,
level:2,
name:"法律服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:402,
id:404,
level:2,
name:"律所",
qualify:{
exter_list:[{
inner_list:[{
name:"《律师事务所执业许可证书》",
url:"http://mmbiz.qpic.cn/mmbiz_png/icTdbqWNOwNRuibColx4vicJTLp4mbxy4QKiavSfx0ymyhXxuFyNTVDFU2IRm8kMbWMUjGwTw6NYRsd2tiakUMplXEw/0?wx_fmt=png"
}]
},{
inner_list:[{
name:"《经司法厅批准成立法律服务机构的文件》",
url:""
}]
}],
remark:"《律师事务所执业许可证书》 或 经司法厅批准成立法律服务机构的文件"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:402,
id:405,
level:2,
name:"招聘/求职（中介类）",
qualify:{
exter_list:[{
inner_list:[{
name:"《人力资源服务许可证》",
url:""
}]
}],
remark:"《人力资源服务许可证》"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:402,
id:406,
level:2,
name:"农林牧渔",
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:402,
id:628,
level:2,
name:"会展服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:402,
id:774,
level:2,
name:"广告/设计",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[1,2,3,4,0]
},{
children:[],
father:402,
id:776,
level:2,
name:"公关/推广/市场调查",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:402,
id:778,
level:2,
name:"公证",
qualify:{
exter_list:[{
inner_list:[{
name:"与公证处的合作协议",
url:""
}]
}],
remark:"与公证处的合作协议"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:402,
id:810,
level:2,
name:"拍卖公司（非文物）",
qualify:{
exter_list:[{
inner_list:[{
name:"《CP备案截图》",
url:""
},{
name:"《拍卖经营批准证书》",
url:""
},{
name:"《营业执照》",
url:""
}]
}],
remark:"营业执照需要核查经营范围含有拍卖"
},
sensitive_type:1,
type_list:[1,2,3,4,0]
},{
children:[],
father:402,
id:812,
level:2,
name:"文物拍卖公司",
qualify:{
exter_list:[{
inner_list:[{
name:"《ICP备案截图》",
url:""
},{
name:"《拍卖经营批准证书》",
url:""
},{
name:"《文物拍卖许可证》",
url:""
},{
name:"《营业执照》",
url:""
}]
}],
remark:"营业执照需要核查经营范围含有拍卖"
},
sensitive_type:1,
type_list:[1,2,3,4,0]
},{
children:[],
father:402,
id:870,
level:2,
name:"典当",
qualify:{
exter_list:[{
inner_list:[{
name:"《典当经营许可证》",
url:""
},{
name:"《特种行业许可证》",
url:""
},{
name:"《ICP备案》",
url:""
}]
}],
remark:"《典当经营许可证》+ 《特种行业许可证》+ ICP备案"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
},{
children:[],
father:402,
id:876,
level:2,
name:"会计师事务所",
qualify:{
exter_list:[{
inner_list:[{
name:"《会计师事务所执业证书》",
url:""
}]
}],
remark:"《会计师事务所执业证书》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:402,
id:878,
level:2,
name:"税务师事务所",
qualify:{
exter_list:[{
inner_list:[{
name:"《税务师事务所执业证书》",
url:""
}]
}],
remark:"《税务师事务所执业证书》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:402,
id:880,
level:2,
name:"一般财务服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[1,2,3,4,0]
},{
children:[],
father:407,
id:408,
level:2,
name:"公益慈善",
qualify:{
exter_list:[{
inner_list:[{
name:"《基金会法人登记证书》",
url:""
}]
},{
inner_list:[{
name:"《慈善组织公开募捐资质证书》",
url:""
}]
}],
remark:"民政部《基金会法人登记证书》或《慈善组织公开募捐资质证书》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:407,
id:630,
level:2,
name:"基金会",
qualify:{
exter_list:[{
inner_list:[{
name:"《基金会法人登记证书》",
url:""
}]
}],
remark:"民政部《基金会法人登记证书》"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:674,
id:676,
level:2,
name:"体育场馆服务",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:674,
id:678,
level:2,
name:"体育赛事",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:674,
id:680,
level:2,
name:"体育培训",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:674,
id:682,
level:2,
name:"在线健身",
qualify:{
exter_list:[]
},
sensitive_type:0,
type_list:[0,1,2,3,4]
},{
children:[],
father:780,
id:782,
level:2,
name:"电商平台",
qualify:{
exter_list:[{
inner_list:[{
name:"《增值电信业务经营许可证》",
url:""
}]
},{
inner_list:[{
name:"《电信与信息服务业务经营许可证》",
url:""
}]
}],
remark:"电商平台为企业或个人提供网上交易的平台，可以理解为多个经营者提供交易的平台，如京东、有赞等。"
},
sensitive_type:1,
type_list:[1,2,3,4]
},{
children:[],
father:868,
id:874,
level:2,
name:"时政信息",
qualify:{
exter_list:[{
inner_list:[{
name:"有资质：《互联网新闻信息服务许可证》",
url:""
}]
},{
inner_list:[{
name:"无资质：ICP备案",
url:""
}]
}],
remark:"有资质则提供：《互联网新闻信息服务许可证》，无资质则提供ICP备案"
},
sensitive_type:1,
type_list:[0,1,2,3,4]
}];
r(),wx.cgiData.cotractor_name&&wx.cgiData.cotractor_id||p.show({
title:"请补全运营者信息",
msg:"你的公众号没有运营者信息，无法开通门店小程序，请先补全。",
buttons:[{
text:"取消",
type:"normal",
click:function(){
this.remove();
}
},{
text:"补全信息",
type:"primary",
click:function(){
this.remove(),location.href=wx.url("/cgi-bin/safecenterstatus?action=admins");
}
}]
});
});