define("device/apply_list.js",["common/wx/Tips.js","common/wx/Cgi.js","common/wx/popup.js","common/wx/dialog.js","biz_common/moment.js","common/wx/pagebar.js","common/wx/tooltips.js","common/qq/jquery.plugin/zclip.js","biz_common/jquery.validate.js"],function(e){
"use strict";
var t=(wx.T,template.render),o=e("common/wx/Tips.js"),r=e("common/wx/Cgi.js"),n=(e("common/wx/popup.js"),
e("common/wx/dialog.js")),i=e("biz_common/moment.js"),a=e("common/wx/pagebar.js"),s=e("common/wx/tooltips.js"),u=wx.cgiData||{},c={
total_quota:"",
used_quota:"",
left_quota:"",
total_order_num:"",
can_apply:"",
acct_status:"",
offset:"",
count:"",
order_list:{}
},m=$.extend({},c,u);
e("common/qq/jquery.plugin/zclip.js"),e("biz_common/jquery.validate.js"),function(){
6==+m.acct_status?$("#js_request").on("click",function(){
if("0"==m.can_apply)n.show({
title:"提示",
type:"info",
msg:"你尚有设备号在审核中，无法申请更多设备号",
mask:!0,
buttons:[{
text:"确定",
click:function(){
this.remove();
}
}]
});else{
var e,i=$(t("tpl_request",{})).popup({
title:"申请设备号",
close:function(){
this.remove();
},
buttons:[{
text:"申请",
click:function(){
if(e.form()){
var t=i.find("form").serialize().param(!0);
r.post({
url:wx.url("/device/device_func_detail?action=apply_order"),
data:t,
mask:!1
},function(e){
if(!e||!e.base_resp)return void o.err("系统错误，请重试");
switch(+e.base_resp.ret){
case 0:
o.suc("提交成功"),setTimeout(function(){
location.reload();
},300);
break;

default:
o.err("提交失败，请重试");
}
});
}
},
type:"primary"
},{
text:"取消",
click:function(){
this.remove();
},
type:"default"
}]
});
$.validator.addMethod("quota_limit",function(e){
var t=+e;
return t&&t>1e5?!1:!0;
},"最多一次申请10万个"),$.validator.addMethod("pnumber",function(e){
return+e>0?!0:!1;
},"数字必须为正整数"),e=i.find("form").validate({
rules:{
quota:{
required:!0,
number:!0,
pnumber:!0
},
capacity:{
required:!0,
number:!0,
pnumber:!0
},
prepare_period:{
required:!0,
number:!0,
pnumber:!0
},
stock_num:{
required:!0,
number:!0,
pnumber:!0
},
remark:{
required:!0
}
},
messages:{
quota:{
required:"请输入申请数量",
number:"申请数量必须是纯数字",
pnumber:"申请数量必须是大于0的整数"
},
capacity:{
required:"请输入日产能",
number:"日产能必须是纯数字",
pnumber:"日产能必须是大于0的整数"
},
prepare_period:{
required:"请输入备料周期",
number:"备料周期必须是纯数字",
pnumber:"备料周期必须是大于0的整数"
},
stock_num:{
required:"请输入物料库存数",
number:"物料库存数必须是纯数字",
pnumber:"物料库存数必须是大于0的整数"
},
remark:{
required:"请输入计划销售渠道"
}
}
});
}
}):($(".js_noauth").show().find("a").on("click",function(){
var e=$(t("tpl_flow",{
step2:+m.acct_status
})).popup({
title:"授权设备号申请流程",
close:function(){
this.remove();
}
});
e.find(".js_copy").zclip({
path:"/mpres/zh_CN/htmledition/plprecorder/biz_web/ZeroClipboard.swf",
copy:function(){
return"wxthing@foxmail.com";
},
afterCopy:function(){
o.suc("复制成功");
}
});
}),$("#js_request").on("click",function(){
n.show({
title:"提示",
type:"info",
msg:"你尚未完成商业化授权，无法申请设备号",
mask:!0,
buttons:[{
text:"查看授权设备号申请流程",
click:function(){
this.remove(),$("#js_subsend").click();
}
},{
text:"取消",
type:"normal",
click:function(){
this.remove();
}
}]
});
})),$(".js_num_apply").text(m.total_quota||"-"),$(".js_num_used").text(m.used_quota||"-"),
$(".js_num_left").text(m.left_quota||"-");
for(var e={
0:"未审核",
1:"审核中",
2:"审核不通过",
3:"审核通过",
4:"发布中",
5:"发布不通过",
6:"发布通过"
},u=m.order_list,c=0,p=u.length;p>c;c++){
var l=u[c].order_status;
u[c].statusname=e[""+l]||"未知",u[c].iserror=2==+l||5==+l?!0:!1,u[c].createtime=i.unix(u[c].create_time).format("YYYY.MM.DD");
}
$("#js_maintb").html(t("tpl_table",{
data:u
})),$(".js_ask").each(function(){
new s({
container:$(this)
});
});
var d=+(m.count||"10"),d=d>0?d:10,f=+m.total_order_num,_=+(m.offset||"1"),_=_>0?_:1;
if(f>d){
var b=_>0?Math.floor(_/d)+1:1;
new a({
container:".js_pager",
perPage:d,
initShowPage:b,
totalItemsNum:f,
first:!1,
last:!1,
startRange:4,
midRange:0,
endRange:1,
isSimple:!0,
callback:function(e){
var t=""+e.perPage*(e.currentPage-1),o=location.href;
return location.href=/([\?&])pageid=\d*/.test(o)?o.replace(/([\?&])pageid=\d*/,"$1pageid="+t):o+"&pageid=%s&order_num=%s".sprintf(t,e.perPage),
!1;
}
});
}
}();
});