define("wxverify/artistreg.js",["common/wx/Cgi.js","wxverify/commonreg.js"],function(e,r,i){
"use strict";
function a(){
$("#artistreg").validate($.extend(!0,{},t,{
rules:{
email:"trimemail",
organization_code:"required",
parent_company:"required",
registered_address:"required",
generic_business_type:{
required:!0,
maxlength:1e3
},
front_business_type:{
required:!0,
maxlength:1e3
},
registered_capital:"required",
organization_code_stuff:"required",
artist_idcard_name:"required",
artist_name:"required",
artist_idcard_num:"required",
artist_magnum_opus:"required",
artist_bank_name:"required",
artist_bank_account:"required",
artist_company:"required",
artist_idcard_stuff:"required",
artist_autorization_vedio:"required"
},
messages:{
name:"企业全称不能为空",
email:"请输入正确的邮箱格式",
parent_company:"隶属企业不能为空",
registered_address:"企业注册地址不能为空",
office_address:"企业办公地址不能为空",
generic_business_type:{
required:"一般经营范围不能为空",
maxlength:"一般经营范围不超过1000字"
},
front_business_type:{
required:"前置许可经营范围不能为空",
maxlength:"前置许可经营范围不能超过1000字"
},
registered_capital:"注册资本金不能为空",
legal_person:"法定代表人/企业负责人姓名不能为空",
account_name:"企业开户名称不能为空",
bank_name:"企业开户银行不能为空",
bank_account:"企业银行账号不能为空",
artist_idcard_name:"艺人身份证姓名不能为空",
artist_name:"艺人艺名不能为空",
artist_idcard_num:"艺人身份证号不能为空",
artist_magnum_opus:"艺人代表作品不能为空",
artist_bank_name:"艺人个人银行账号开户行不能为空",
artist_bank_account:"艺人个人银行账号不能为空",
artist_company:"艺人经纪公司不能为空",
artist_idcard_stuff:"艺人身份证彩色扫描件不能为空",
artist_autorization_vedio:"艺人授权视频不能为空"
}
}));
}
{
var t=(e("common/wx/Cgi.js"),e("wxverify/commonreg.js"));
t.commonMsgs;
}
i.exports=function(){
a();
};
});