define("scan/biz_category.js",[],function(){
"use strict";
var i={},m={},e=["441417026"],l=[{
name:"食品饮料",
id:"200525513",
sub:[{
name:"食品/茶叶/特产/滋补品",
id:"538071212",
file:[{
menu:null,
file:["工业产品生产许可证（证件编号前缀为：QS或SC）"]
}]
},{
name:"有机食品",
id:"200531966",
file:[{
menu:null,
file:["工业产品生产许可证（证件编号前缀为：QS或SC）（或2009年6月1日前获批的食品卫生许可证）"]
},{
menu:null,
file:["有机产品认证证书"]
}]
},{
name:"调味品",
id:"200531967",
file:[{
menu:null,
file:["工业产品生产许可证（证件编号前缀为：QS或SC）"]
}]
},{
name:"水果生鲜",
id:"200531968",
file:[]
},{
name:"饮料",
id:"200531969",
file:[{
menu:null,
file:["工业产品生产许可证（证件编号前缀为：QS或SC）"]
}]
},{
name:"酒类",
id:"200531971",
file:[{
menu:null,
file:["工业产品生产许可证（证件编号前缀为：QS或SC）"]
}]
}]
},{
name:"母婴用品",
id:"200525514",
sub:[{
name:"奶粉/辅食/营养品",
id:"538104511",
file:[{
menu:null,
file:["工业产品生产许可证（证件编号前缀为：QS或SC）"]
}]
},{
name:"童装/童鞋/亲子装/配饰",
id:"537893413",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"玩具/模型/动漫/早教/益智",
id:"538088633",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"孕产妇服饰/用品/营养品",
id:"538104513",
file:[{
menu:"孕产妇服饰/用品",
file:["工业产品生产许可证"]
},{
menu:"孕产妇营养品",
file:["工业产品生产许可证（证件编号前缀为：QS或SC）"]
}]
},{
name:"纸尿裤/洗护/喂哺/推车床",
id:"538104512",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
}]
},{
name:"医药用品",
id:"200525516",
sub:[{
name:"成人用品/避孕/计生用品",
id:"538096864",
file:[{
menu:"避孕/计生药品",
file:["药品生产许可证"]
},{
menu:"医学性质的避孕/计生器械",
file:["医疗器械经营企业许可证"]
}]
},{
name:"医药用品",
id:"538104253",
file:[{
menu:"非处方药品",
file:["《药品注册批件》（含有药品批准文号）"]
},{
menu:"医疗器械",
file:["医疗器械生产企业许可证"]
},{
menu:"医用卫生材料及敷料、棉布、弹力布及其制品",
file:["第一类医疗器械生产备案"]
},{
menu:"中药饮片",
file:["药品生产许可证","药品GMP证书"]
},{
menu:"中药提取物",
file:["中药提取物生产备案"]
}]
}]
},{
name:"美容美妆",
id:"200525517",
sub:[{
name:"彩妆/香水/美妆工具",
id:"538112978",
file:[{
menu:null,
file:["《工业产品生产许可证》或《化妆品生产企业卫生许可证书》"]
}]
},{
name:"美发护发/假发",
id:"538112979",
file:[{
menu:"一般美发护发/假发",
file:["《工业产品生产许可证》或《化妆品生产企业卫生许可证书》"]
},{
menu:"特殊美发护发/假发",
file:["特殊用途化妆品卫生许可证批件复印件(育发类、染发类、烫发类、脱毛类)"]
}]
},{
name:"美容护肤/美体/精油",
id:"537890913",
file:[{
menu:"一般美容护肤/美体/精油",
file:["《工业产品生产许可证》或《化妆品生产企业卫生许可证书》"]
},{
menu:"特殊美容护肤/美体/精油",
file:["特殊用途化妆品卫生许可证批件复印件(美乳类、健美类、除臭类、祛斑类、防晒类化妆品)"]
}]
}]
},{
name:"日用百货",
id:"200525518",
sub:[{
name:"家纺-床品/抱枕/毛巾/拖鞋",
id:"537906649",
file:[]
},{
name:"家用-居家日用/餐厨用品/清洁洗护",
id:"537898967",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"卫生巾、消毒液等消毒用品",
id:"213346811",
file:[{
menu:null,
file:["消毒产品生产企业卫生许可证"]
}]
}]
},{
name:"家电数码",
id:"200525519",
sub:[{
name:"MP3/MP4/录音笔/电纸书",
id:"538072052",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"笔记本/台式/一体/平板电脑",
id:"538112937",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"电脑硬件/周边/网络设备",
id:"537870913",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"电玩/游戏机/配件/游戏软件",
id:"538096552",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"国货精品数码",
id:"538111060",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"家用电器（大家电）",
id:"537898965",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"冰箱/空调/冰柜/制冷家用电器",
id:"213298801",
file:[{
menu:null,
file:["中国国家强制性产品认证证书"]
}]
},{
name:"品牌手机",
id:"538371746",
file:[{
menu:null,
file:["电信设备进网许可证"]
}]
},{
name:"数码配件",
id:"537898921",
file:[{
menu:"电池",
file:["中国国家强制性产品认证证书"]
},{
menu:"其他数码配件",
file:["工业产品生产许可证"]
}]
},{
name:"数码相机/摄像机/单反/器材",
id:"537874913",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
}]
},{
name:"文化玩乐",
id:"200525520",
sub:[{
name:"办公/电子辞典/文具",
id:"537898958",
file:[{
menu:"电子辞典",
file:["中国国家强制性产品认证证书","工业产品生产许可证"]
},{
menu:"办公",
file:["工业产品生产许可证"]
},{
menu:"文具",
file:[]
}]
},{
name:"乐器及配件",
id:"538103269",
file:[]
},{
name:"宠物/宠物食品及用品",
id:"538100515",
file:[{
menu:"宠物食品",
file:["工业产品生产许可证"]
},{
menu:"宠物食品添加剂",
file:["饲料添加剂生产许可证"]
},{
menu:"宠物用品",
file:[]
}]
},{
name:"花卉绿植",
id:"213218815",
file:[]
}]
},{
name:"女装男装",
id:"200525521",
sub:[{
name:"精品男装",
id:"401797205",
file:[]
},{
name:"时尚女装/中老年装/婚纱礼服",
id:"401797206",
file:[]
}]
},{
name:"内衣配饰",
id:"200525522",
sub:[{
name:"男装配件",
id:"538112994",
file:[]
},{
name:"女士内衣/男士内衣/家居服/袜子",
id:"537898070",
file:[]
},{
name:"女士配件/围巾/帽子/眼镜/手套",
id:"537891913",
file:[]
}]
},{
name:"鞋类箱包",
id:"200525523",
sub:[{
name:"男鞋",
id:"537905079",
file:[]
},{
name:"女鞋",
id:"537891948",
file:[]
},{
name:"热销女包/男包/功能箱包",
id:"538082593",
file:[]
}]
},{
name:"运动户外",
id:"200525524",
sub:[{
name:"户外运动/登山野营/旅行装备",
id:"537876982",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"球类/运动器械/瑜伽健身游泳",
id:"537876913",
file:[{
menu:null,
file:["工业产品生产许可证"]
}]
},{
name:"运动服饰/配件/包袋",
id:"537905439",
file:[]
},{
name:"运动鞋",
id:"537876929",
file:[]
}]
},{
name:"珠宝配饰",
id:"200525525",
sub:[{
name:"时尚饰品",
id:"537872913",
file:[]
},{
name:"珠宝钻石",
id:"537903127",
file:[{
menu:"珠宝",
file:["珠宝玉石首饰鉴定证书"]
},{
menu:"钻石",
file:["钻石分级证书（或者钻石质量保证书）"]
}]
},{
name:"手表名品",
id:"213298802",
file:[]
}]
},{
name:"家居建材",
id:"200525527",
sub:[{
name:"家装-灯饰/厨卫/建材/涂料",
id:"537898968",
file:[{
menu:"家装-厨卫/建材/涂料",
file:["安全生产许可证"]
},{
menu:"家装-灯饰",
file:["安全生产许可证","中国国家强制性产品认证证书"]
},{
menu:"五金电工",
file:["工业产品生产许可证"]
}]
},{
name:"家饰-装饰/摆设/布艺/十字绣",
id:"538112993",
file:[]
},{
name:"家具-床/沙发/桌/柜/箱架",
id:"537898966",
file:[]
}]
},{
name:"汽车及配件",
id:"200525528",
sub:[{
name:"汽车/摩托/配件/服务",
id:"537879913",
file:[{
menu:"汽车用品",
file:["中国国家强制性产品认证证书"]
},{
menu:"摩托车用品",
file:["中国国家强制性产品认证证书"]
},{
menu:"维修保养服务",
file:["机动车维修经营许可证"]
},{
menu:"维修保养产品",
file:[]
}]
}]
},{
name:"香烟",
id:"441417028",
sub:[{
name:"香烟",
id:"441417026",
file:[{
menu:null,
file:["烟草专卖生产企业许可证"]
}]
}]
}],c={
"营业执照":{
desc:"上传原件或复印件，(由各级工商行政机关颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNmG8VOB170diagNZpLNGLMFek3Se3UXv0X15ALzG4YyoSgHVJicI3vMCg/0"
},
"补充资质":{
optional:!0,
desc:"若资质主体与公众号认证主体不一致，请在此上传授权书，说明授权关系",
sample:"/htmledition/res/scan/%E6%8E%88%E6%9D%83%E4%B9%A6%E6%A8%A1%E6%9D%BF.doc",
sampleName:"授权书模版下载"
},
"国产保健食品批准证书":{
desc:"上传原件或复印件，(由各省级卫生厅、各市县卫生局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNCcricEPzePuDXJzlggYp6vsbJafA11wJeKT3luLH1y5ay4zgwcK5l1Q/0"
},
"食品卫生许可证或保健食品GMP证":{
desc:"上传原件或复印件，(食品生产许可证：由各市县卫生局颁发/保健食品GMP证书：由各省级卫生厅、食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNjPDibicYhppljS1icG73uutpKVAJfibEr3pzq940ib9E2cJplxjrT1GAgBQ/0"
},
"工业产品生产许可证":{
desc:"上传原件或复印件，(由国家质量监督检验检疫总局、省级质量技术监督局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNVzfNteHzMvCCk6GKycfiapq3lgM5wUYNRG15OSFEVecicRc1Eu1coQIg/0"
},
"工业产品生产许可证（证件编号前缀为：QS或SC）":{
desc:"上传原件或复印件，(由国家质量监督检验检疫总局、省级质量技术监督局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNVzfNteHzMvCCk6GKycfiapq3lgM5wUYNRG15OSFEVecicRc1Eu1coQIg/0"
},
"工业产品生产许可证（证件编号前缀为：QS或SC）（或2009年6月1日前获批的食品卫生许可证）":{
desc:"上传原件或复印件，(由国家质量监督检验检疫总局、省级质量技术监督局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNVzfNteHzMvCCk6GKycfiapq3lgM5wUYNRG15OSFEVecicRc1Eu1coQIg/0"
},
"卫生部名单":{
desc:"上传原件或复印件，(由国家烟草专卖局颁发，复印件请务必加盖公司公章)",
sample:""
},
"烟草专卖生产企业许可证":{
desc:"上传原件或复印件，(由国家烟草专卖局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRna42FI242LQCiaVXOf9v61WhMWoIxvHricx110zaDByianepkGdHGzzg50A7JzQFZfhwWicQTdGzZRA/0?wx_fmt=jpeg"
},
"烟草专卖经营企业许可证（特种烟草）":{
desc:"上传原件或复印件，(由各市县商务局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDN5a3opSPxVDWSO1liaeVjByW6iap0WNKJdGepibXxfhc3ASEcD2OFoY41w/0"
},
"酒类产销许可证":{
desc:"上传原件或复印件，(由各市县卫生局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNXzGAIYs6x6ubT87N6WF1S9OpjAJjWicdRQ35dhrWXtp2jpJovib6UOaw/0"
},
"《药品注册批件》（含有药品批准文号）":{
desc:"上传原件或复印件，(由国家食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNtxLr4QYr4hhBmibicLR6YSBP4GtZUZUlP8AGjH2kEjy6F77UVHLwib5XQ/0"
},
"药品生产许可证":{
desc:"上传原件或复印件，(由各省级食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDN1usm6esaEA0z6YxNHzFl7jjCShhODCf68KEtVWxC0V8Cu0MhhC38MA/0"
},
"医疗器械生产企业许可证":{
desc:"上传原件或复印件，(由各省级食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNMq6WXkOVjMfRnH21f7xbPQIiakZngFEBIZ85BeG9aQzic006WjXZibFtQ/0"
},
"医疗器械经营企业许可证":{
desc:"上传原件或复印件，(由各市级食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNN0yibJGKGbr9b3OicrdMiaBuoX1VU7ibzVVhs7YwXy24176KlV8eykia4Zw/0"
},
"化妆品生产许可证":{
desc:"上传原件或复印件，(由国家质量监督检验检疫总局、省级质量技术监督局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNzlJrPtI7RNEGMe0YrWIGlgic6Eu0KbjxHPM8ibGbsficMMIW4OX8BKkYA/0"
},
"化妆品生产企业卫生许可证":{
desc:"上传原件或复印件，(由省级食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDN5YQh3PeI2prQJTggueurjSVCFeYZ1ct3DUNJntu6IboYaBMBUOZENQ/0"
},
"特殊用途化妆品卫生许可批件复印件":{
desc:"上传原件或复印件，(由国家食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDND7snHLO4HickeiaZJQKSiaUkmJGHR7LLnSKic1sNJeEkicb3MW8eMWkbibzw/0"
},
"中国国家强制性产品认证证书":{
desc:"上传原件或复印件，(由中国质量认证中心颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNv0ia9KU9AUlYemhk8DQkLvZnhe87tqO5Bsxe5O9X7dnic2QfXn7ibkNhA/0"
},
"饲料添加剂生产许可证":{
desc:"上传原件或复印件，(由国家农业部颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNUoaKPNmYBQHSDAibUVVP1AGWf39lmSMsYhy2diaJ6v22wdhmf4J8Io4w/0"
},
"珠宝玉石首饰鉴定证书":{
desc:"上传原件或复印件，(由NCGTC颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNS1Aag7uicV4KV99fANibAicVsBsiaK4oYo2KzCqU6KAkcdqnNGl4CYgSkQ/0"
},
"出版物经营许可证":{
desc:"上传原件或复印件，(由地方新闻出版局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDN8Bo2smdupfI5icwPq5JKuSU77KLgqqNAowv1oia2uicjIOAdGlZNBSSWw/0"
},
"互联网出版许可证":{
desc:"上传原件或复印件，(由新闻出版总署颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNfyVwpoicbANPovPSicmnZ1ictcDGcSBoPbMUgr3pchlcXH6yZbIhWtLaQ/0"
},
"广播电视节目制作经营许可证":{
desc:"上传原件或复印件，(由广电总局审批、省级广播电影电视局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNIibiaojhScmlFNJCXrzaOG8cPNj3ozIfKj0fnmcdsicPwLXcNvKA5Q8KA/0"
},
"安全生产许可证":{
desc:"上传原件或复印件，(由国务院、省级安全生产监督管理部门颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNqChXGrgPnY1GBmLpVHPpXFpOpDDg0vurG9YdDicia1ficm2WD0XOHsicwQ/0"
},
"机动车维修经营许可证":{
desc:"上传原件或复印件，(由各县级道路运输管理机构颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNPaPib6iaQoZWdcymW2iadbhZVlEVtf19L4KfnfJHD49gpribbialLqLhuxg/0"
},
"快递业务经营许可证":{
desc:"上传原件或复印件，(由中国务院、省级邮政管理部门颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNj5COL7vXyPZ2jKuJic0ECIS7tZfuS1wdKTcXaSxNicrJ6CkV97vBjkMg/0"
},
"食品卫生许可证":{
desc:"上传原件或复印件，(由各市县卫生局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNjPDibicYhppljS1icG73uutpKVAJfibEr3pzq940ib9E2cJplxjrT1GAgBQ/0"
},
"有机产品认证证书":{
desc:"上传有机产品认证信息截图。请登录国家认监委网站“中国食品农产品认证信息系统”:http://ffip.cnca.cn/ffip/publicquery/certSearch.jsp ，将查询结果截图上传",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDNfT46HtxBLkBUxwDWxkJnkBNnnxXuZhxo2o2ocR3rpc8TXNaCce9plg/0"
},
"特殊用途化妆品卫生许可证批件复印件(育发类、染发类、烫发类、脱毛类)":{
desc:"上传原件或复印件，(由国家食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDND7snHLO4HickeiaZJQKSiaUkmJGHR7LLnSKic1sNJeEkicb3MW8eMWkbibzw/0"
},
"特殊用途化妆品卫生许可证批件复印件(美乳类、健美类、除臭类、祛斑类、防晒类化妆品)":{
desc:"上传原件或复印件，(由国家食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRzNyksbtsXmqYAVlgtRaDND7snHLO4HickeiaZJQKSiaUkmJGHR7LLnSKic1sNJeEkicb3MW8eMWkbibzw/0"
},
"食品流通许可证":{
desc:"上传原件或复印件，(由工商行政管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztBQzJrJc04lxDDZwxOSdOVolCiajU8icX3yA9dzCVGBH2CjnKKpZ9Pfog/0?wx_fmt=png"
},
"中华人民共和国海关进口货物报关单（有效期1个月内）":{
desc:"上传原件或复印件，(由海关部门颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztHTtH0xibaMmgib03RfSaHk36KQkiazhZMHXO7QmCnyibI1P5DGbo7zN5vw/0?wx_fmt=jpeg"
},
"中华人民共和国海关进口货物报关单（有效期6个月内）":{
desc:"上传原件或复印件，(由海关部门颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztHTtH0xibaMmgib03RfSaHk36KQkiazhZMHXO7QmCnyibI1P5DGbo7zN5vw/0?wx_fmt=jpeg"
},
"中华人民共和国海关进口货物报关单（有效期9个月内）":{
desc:"上传原件或复印件，(由海关部门颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztHTtH0xibaMmgib03RfSaHk36KQkiazhZMHXO7QmCnyibI1P5DGbo7zN5vw/0?wx_fmt=jpeg"
},
"中华人民共和国海关进口货物报关单（有效期12个月内）":{
desc:"上传原件或复印件，(由海关部门颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztHTtH0xibaMmgib03RfSaHk36KQkiazhZMHXO7QmCnyibI1P5DGbo7zN5vw/0?wx_fmt=jpeg"
},
"中华人民共和国出入境检验检疫卫生证书（有效期1个月内）":{
desc:"上传原件或复印件，(由出入境检验检疫局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztFQJyR3892TeFdllGJNemLA5KRCYNpANhRPwGzdor8oTPxnAS9ZdGlQ/0?wx_fmt=png"
},
"中华人民共和国出入境检验检疫卫生证书（有效期6个月内）":{
desc:"上传原件或复印件，(由出入境检验检疫局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztFQJyR3892TeFdllGJNemLA5KRCYNpANhRPwGzdor8oTPxnAS9ZdGlQ/0?wx_fmt=png"
},
"中华人民共和国出入境检验检疫卫生证书（有效期9个月内）":{
desc:"上传原件或复印件，(由出入境检验检疫局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztFQJyR3892TeFdllGJNemLA5KRCYNpANhRPwGzdor8oTPxnAS9ZdGlQ/0?wx_fmt=png"
},
"中华人民共和国出入境检验检疫卫生证书（有效期12个月内）":{
desc:"上传原件或复印件，(由出入境检验检疫局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvztFQJyR3892TeFdllGJNemLA5KRCYNpANhRPwGzdor8oTPxnAS9ZdGlQ/0?wx_fmt=png"
},
"《酒类流通备案登记表》（或《酒类商品零售许可证》、《酒类批发经营许可证》、《酒类产销许可证》）":{
desc:"上传原件或复印件，(复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIyFtJoCxeQwNKZWHFeq4JGbZ0IGJLyZbezbPteUxTd2omGMK4HawSFgDMWqxGrQjLA/0?wx_fmt=jpeg"
},
"《进口药品注册证》或《医药产品注册证》":{
desc:"上传原件或复印件，(复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIyFtJoCxeQwNDXHUJ6J8UEF1GibP8BJ1e0Ut7gS23uNIQpRtEiczg8ed3QO6GmmajKPw/0?wx_fmt=jpeg"
},
"进口非特殊用途/特殊用途化妆品备案":{
desc:"上传原件或复印件，(由国家食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldI7rzl9pgoQ1MXey1X37xGRCmV6CI1xicmuZVSVCQWAF5Y9H1hjx1sVnhVc2L2769ekg/0?wx_fmt=jpeg"
},
"钻石分级证书（或者钻石质量保证书）":{
desc:"上传原件或复印件，(复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIicId2zmqtvzt6pHYZibRovGOVb8uXgEhpqby7CDJA4NxGFHicH9Zf5V2T8FonYicH9Eibw/0?wx_fmt=png"
},
"消毒产品生产企业卫生许可证":{
desc:"上传原件或复印件，(由卫生局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNTAJ83Pib2ldIwuyYF5cFEQtbUUR2EVVcA6b3zRzJKKMKc0VHc02Qld7BjsqMfFb7t1jnmTRiba59GA/0?wx_fmt=png"
},
"电信设备进网许可证":{
desc:"电信设备进网许可证：上传原件或复印件，(由工业和信息化部颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNQGEHZ5JY4H8o3jfBa3DicsGy1vr7m6R6s7A5Gv6OansNwZfX53zms3aKRiaRcbSc45C7eiaaxnd6UibQ/0?wx_fmt=jpeg"
},
"《工业产品生产许可证》或《化妆品生产企业卫生许可证书》":{
desc:"上传原件或复印件，(《工业产品生成许可证》由国家质量监督检验检疫总局、省级质量技术监督局颁发，《化妆品生产企业卫生许可证》由省级食品药品监督管理局颁发，复印件请务必加盖公司公章)",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRna42FI242LQnFwp6V8asLeFyUUJPllQMrogicqKmkmGOfyHDnJLfdOluDPxp5RAAqY5YLsfkrVEQ/0?wx_fmt=png"
},
"中药提取物生产备案":{
desc:"上传原件或复印件，（由国家药品监督管理局颁发，复印件请务必加盖公司公章）",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRna42FI242Lcia07jQodd2FicdCtjv9KyJQj3K7nmVaYDWNfjAglrCyoSbO5GhG4dAQxriaujXBTibfA/0?wx_fmt=png"
},
"药品GMP证书":{
desc:"上传原件或复印件，（由国家药品监督管理局颁发，复印件请务必加盖公司公章）",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRna42FI242Lcia07jQodd2FOwnEIZUUicQX6OVvMGVWR6r7iaET7vnZGwE1ibLKamCGlSotCqzwTe7ag/0?wx_fmt=jpeg"
},
"第一类医疗器械生产备案":{
desc:"上传原件或复印件，（由国家食品药品监督管理局颁发，复印件请务必加盖公司公章）",
sample:"http://mmbiz.qpic.cn/mmbiz/icTdbqWNOwNRna42FI242Lcia07jQodd2FE98C8YjeTd4MU3o9ibvm1Hico9GwONuETicQriclRCpbwgSj9aep2gcmug/0?wx_fmt=jpeg"
}
};
for(var b in c)c[b].name=b;
for(var n=wx.cgiData.category_white_list?wx.cgiData.category_white_list.list||[]:[],t=l.length,a=0,d=0;d<n.length;d++)n[d]=n[d]+"";
for(var d=0;t>d;d++){
a=l[d].sub.length;
for(var s=0;a>s;s++){
var p=l[d].sub[s].id;
$.inArray(p,e)>-1&&-1==$.inArray(p,n)&&(l[d].sub.splice(s,1),s--,a--);
}
0==l[d].sub.length&&(l.splice(d,1),d--,t--);
}
for(var d=0;d<l.length;d++){
l[d].value=l[d].id;
for(var s=0;s<l[d].sub.length;s++){
l[d].sub[s].value=l[d].sub[s].id;
for(var N=0;N<l[d].sub[s].file.length;N++)for(var f=0;f<l[d].sub[s].file[N].file.length;f++){
var z=l[d].sub[s].file[N].file[f];
"string"==typeof z&&c[z]&&(l[d].sub[s].file[N].file[f]=c[z]);
}
}
}
for(var d=0;d<l.length;d++){
i[l[d].id]=l[d];
for(var s=0;s<l[d].sub.length;s++)i[l[d].sub[s].id]=l[d].sub[s];
}
for(var d=0;d<l.length;d++)for(var s=0;s<l[d].sub.length;s++)m[l[d].sub[s].id]=l[d];
return{
category:l,
categoryMap:i,
categoryParentMap:m,
getCategory:function(m){
return i[m+""]||null;
},
getSubCategories:function(m){
var e=i[m+""];
return e&&e.sub?e.sub:[];
},
getParentCategory:function(i){
return m[i+""]||null;
}
};
});