define("ad_system/client_pay.js",["biz_web/ui/dropdown.js","biz_common/moment.js","biz_web/ui/dateRange.js","common/wx/Cgi.js","common/wx/pagebar.js","ad_system/helper.js","biz_common/jquery.validate.js","common/wx/popup.js","biz_web/ui/checkbox.js","common/wx/region.js","common/wx/Tips.js","common/wx/top.js"],function(e){
"use strict";
function t(){
p=r({
container:"#dateRangeFlow",
startDate:s.unix(wx.data.time).add("days",-29).format("YYYY-MM-DD"),
endDate:s.unix(wx.data.time).format("YYYY-MM-DD"),
theme:"ta",
isTodayValid:!0,
success:function(){
a(1,0,!0);
}
}),h=r({
container:"#dateRangeDetail",
startDate:s.unix(wx.data.time).add("days",-6).format("YYYY-MM-DD"),
endDate:s.unix(wx.data.time).format("YYYY-MM-DD"),
theme:"ta",
isTodayValid:!0,
success:function(){
a(2,0,!0);
}
});
}
function i(){
var e=!0;
$("#detailNav").click(function(){
$(this).hasClass("selected")||($("#detail").show(),$("#flow").hide(),$(this).addClass("selected").siblings().removeClass("selected")),
e&&(a(2,0,!0),e=!1);
}),$("#flowNav").click(function(){
$(this).hasClass("selected")||($("#flow").show(),$("#detail").hide(),$(this).addClass("selected").siblings().removeClass("selected")),
e&&(a(1,0,!0),e=!1);
}),"bill"==wx.cgiData.source&&$("#flowNav").click(),$("#pay").click(function(){
var e="/merchant/ad_client_pay?action=add_recharge&token="+wx.data.t+"&money=",t=$("#payTpl").popup({
title:"充值",
className:"recharge_box",
buttons:[{
text:"去财付通充值",
click:function(){
t.find(".jsPriceOther").is(".selected")?i.form()&&(window.open(e+100*t.find("input[name=price]").val()),
this.remove()):(window.open(e+100*t.find(".selected").data("value")),this.remove());
},
type:"primary"
},{
text:"取消",
click:function(){
this.remove();
}
}],
close:function(){
this.remove();
}
}),i=t.find("#payForm").validate({
rules:{
price:{
number:!0,
required:!0,
min:1e3,
max:999999
}
},
messages:{
price:{
number:"请输入1000-999999间的整数",
require:"请输入1000-999999间的整数",
min:"请输入1000-999999间的整数",
max:"请输入1000-999999间的整数"
}
}
});
t.find(".jsPrice").click(function(){
$(".jsPrice,.jsPriceOther").removeClass("selected"),$(this).addClass("selected"),
t.find("#payForm").hide();
}),t.find(".jsPriceOther").click(function(){
$(".jsPrice,.jsPriceOther").removeClass("selected"),$(this).addClass("selected"),
t.find("#payForm").show();
});
});
}
function a(e,t,i){
e=e||0,t=t||0;
var a={
cont_type:e,
begin:t,
count:10,
out_type:0
};
2==e?(a.start_date=h.getCurrentDate().startDate,a.end_date=h.getCurrentDate().endDate):(a.start_date=p.getCurrentDate().startDate,
a.end_date=p.getCurrentDate().endDate),s(a.end_date,"YYYY-MM-DD").add("days",1).unix()>wx.data.time?$("#desc").show():$("#desc").hide(),
$("#start").text(s.unix(a.start).format("YYYY-MM-DD")),$("#end").text(s.unix(a.end).format("YYYY-MM-DD")),
d.get({
url:"/merchant/ad_client_pay?action=recharge_info",
data:a
},function(t){
0==t.base_resp.ret?($("#expense_all").text(t.expense_all/100),$("#balance_now").text(t.balance_now/100),
n(e,t.pay_info_list,t.total_num,i)):b.err();
});
}
function n(e,t,i,n){
2==e?t.length>0?($("#noListDetail").hide().siblings().show(),$("#detailList").html(template.render("tpl",{
data:t
})),$("#detailList tr:odd").find("td").addClass("row_hint"),n&&new l({
container:"#pageBarDetail",
totalItemsNum:i,
isSimple:!0,
callback:function(e){
a(2,10*(e.currentPage-1));
}
})):$("#noListDetail").show().siblings().hide():t.length>0?($("#noListFlow").hide().siblings().show(),
$("#flowList").html(template.render("tpl2",{
data:t
})),$("#flowList tr:odd").find("td").addClass("row_hint"),n&&new l({
container:"#pageBarFlow",
totalItemsNum:i,
isSimple:!0,
callback:function(e){
a(1,10*(e.currentPage-1));
}
})):$("#noListFlow").show().siblings().hide();
}
function o(){
u=$("#billTpl").popup({
title:"发票信息",
buttons:[{
text:"保存",
click:function(){
if(m.form()){
var e=f.getAll(!0);
if(null==e.province||-1==e.province)b.err("请选择省份");else if(null==e.city||-1==e.city)b.err("请选择城市");else{
var t={
hasBill:1,
head:$(m.currentForm).find("input[name=head]").val(),
contact:$(m.currentForm).find("input[name=contact]").val(),
province:e.province,
city:e.city,
address:$(m.currentForm).find("input[name=address]").val(),
phone:$(m.currentForm).find("input[name=phone]").val(),
code:$(m.currentForm).find("input[name=code]").val()
};
c(t,this);
}
}
},
type:"primary"
},{
text:"取消",
click:function(){
this.remove();
}
}],
close:function(){
this.remove();
}
}),m=u.find(".jsForm").validate({
rules:{
head:{
required:!0
},
address:{
required:!0
},
contact:{
required:!0,
maxlength:10
},
code:{
required:!0,
number:!0
},
phone:{
required:!0,
number:!0
}
}
}),$("input[type=radio]").checkbox(),$("input[type=radio]").change(function(){
0==$(this).data("value")?(u.find(".jsForm1").show(),u.find(".jsForm2").hide()):(u.find(".jsForm1").hide(),
u.find(".jsForm2").show());
}),f=new w(wx.cgiData.hasBill?{
container:"#area",
data:{
country:"中国",
province:wx.cgiData.bill.province,
city:wx.cgiData.bill.city
},
onChange:function(){
$("#area").children().eq(0).hide();
}
}:{
container:"#area",
data:{
country:"中国"
},
onChange:function(){
$("#area").children().eq(0).hide();
}
});
}
function c(e,t){
var i={
need_invoice:e.hasBill,
invoice_title:e.head,
invoice_receiver:e.contact,
invoice_receiver_province:e.province,
invoice_receiver_city:e.city,
invoice_receiver_addr:e.address,
invoice_receiver_mobile:e.phone,
post_code:e.code
};
d.post({
url:"/merchant/ad_client_pay?action=update_invoice",
data:i
},function(i){
0==i.base_resp.ret?(0==e.hasBill?(wx.cgiData.bill={},$("#bill").hide().siblings().show()):(wx.cgiData.hasBill=e.hasBill,
wx.cgiData.bill=e,$("#head").text(e.head),$("#billDetail").text(e.contact+"  "+e.province+e.city+e.address+"  "+e.phone+"  "+e.code),
$("#bill").show().siblings().hide(),$("#modify").show()),$("#billTxt").show(),t.remove()):b.err();
});
}
{
var s=(e("biz_web/ui/dropdown.js"),e("biz_common/moment.js")),r=e("biz_web/ui/dateRange.js"),d=e("common/wx/Cgi.js"),l=e("common/wx/pagebar.js");
e("ad_system/helper.js");
}
e("biz_common/jquery.validate.js"),e("common/wx/popup.js"),e("biz_web/ui/checkbox.js");
var m,u,h,p,f,w=e("common/wx/region.js"),b=e("common/wx/Tips.js"),v=e("common/wx/top.js");
new v("#topTab",v.DATA.adClient).selected("adclientpay"),$("#billBt").click(function(){
o();
}),$("#modify").click(function(){
o(),Object.each(wx.cgiData.bill,function(e,t){
e&&t&&(e+="",u.find(".jsForm").find("input[name="+t+"]").val(e.html(!1)));
});
}),function(){
t(),i(),a(2,0,!0);
}();
});