define("wxverify/commonreg_141210.js",["common/wx/Cgi.js","common/wx/dialog.js","biz_web/lib/store.js","common/wx/Tips.js","common/qq/queryString.js"],function(e,r,i){
"use strict";
function a(e){
var r=$(e).serializeObject(),i={};
for(var a in r)if(a.endsWith("_telephone1")||a.endsWith("_telephone2")){
var t=a.indexOf("_telephone1");
if(0>t&&(t=a.indexOf("_telephone2")),t){
var o=a.substring(0,t);
i[o]=r[o+"_telephone1"]&&r[o+"_telephone2"]?r[o+"_telephone1"]+"-"+r[o+"_telephone2"]:"";
}
}else i[a]=$.trim(r[a]);
return i.mp_operator_phone&&(/^\+/.test(i.mp_operator_phone)||(i.mp_operator_phone="+86"+i.mp_operator_phone)),
i;
}
var t=e("common/wx/Cgi.js"),o=e("common/wx/dialog.js"),n=e("biz_web/lib/store.js"),_="__draft__"+wx.data.uin,s="__draft__time__"+wx.data.uin,d=e("common/wx/Tips.js"),c=e("common/qq/queryString.js");
$.validator.addMethod("scale_verify",function(){
var e=!1;
return $("input[scale_proof='1']").each(function(){
""!=$(this).val()&&(e=!0);
}),e;
},"请至少提交一项");
var u={
telephone:"请输入正确的电话号码，例如：020 - XXXXXXX",
email:"请输入正确的邮箱格式",
idcard:"身份证格式不正确，或者年龄未满18周岁，请重新填写。",
mobile:"请输入正确的手机号码",
file:"未选择文件",
name:"名字为1到20个中英文"
};
i.exports={
rules:{
name:{
required:!0
},
scale:{
required:function(){
return"4"==wx.cgiData.tmp_service_type?!0:!1;
},
number:!0
},
extra_scale:{
number:!0,
required:"#has_extra_scale:checked"
},
social_insure_scale_stuff:{
scale_verify:!0
},
earnings_scale_stuff:{
scale_verify:!0
},
individual_tax_scale_stuff:{
scale_verify:!0
},
working_place_scale_stuff:{
scale_verify:!0
},
biz_tel_scale_stuff:{
scale_verify:!0
},
wages_paying_scale_stuff:{
scale_verify:!0
},
relation_proof_stuff:{
required:"#has_extra_scale:checked"
},
partner_scale_proof_stuff:{
required:"#has_extra_scale:checked"
},
email:{
trimemail:!0
},
registered_id:{
required:!0
},
legal_person:{
required:!0
},
bank_name:{
required:!0
},
account_name:{
required:!0
},
bank_account:{
required:!0
},
mp_operator_name:{
required:!0
},
nick_name:{
required:!0,
byteRangeLength:[4,32]
},
keywords:{
required:!0
},
registered_address:{
required:!0
},
mp_operator_phone:{
mobile:!0
},
mp_operator_tel:{
required:!0
},
mp_operator_email:{
required:!0,
trimemail:!0
},
mp_operator_idcard_name:{
required:!0
},
mp_operator_idcard_number:{
required:!0
},
business_license_stuff:{
required:!0
},
application_letter:{
required:!0
},
mp_operator_idcard_stuff:{
required:!0
},
mp_operator_idcard_back_stuff:{
required:!0
},
soso_map_pos:{
required:!0
},
office_address:{
required:!0
},
office_phone:{
required:!0
}
},
messages:{
name:{
required:"机构名称不能为空"
},
email:{
trimemail:"请输入正确的邮箱格式"
},
organization_code:{
required:"组织机构代码不能为空"
},
legal_person:{
required:"法定代表人/负责人姓名不能为空"
},
registered_id:{
required:"工商执照注册号不能为空"
},
keywords:{
required:"相关关键词不能为空"
},
bank_name:{
required:"机构开户银行不能为空"
},
account_name:{
required:"开户名称不能为空"
},
bank_account:{
required:"机构银行账号不能为空"
},
mp_operator_name:{
required:"帐号运营者姓名不能为空"
},
nick_name:"认证后公众号名称为2到16个字",
mp_operator_idcard_name:{
required:"帐号运营者身份证件类型不能为空"
},
mp_operator_idcard_number:{
required:"运营人员身份证号码不能为空"
},
mp_operator_idcard_back_stuff:{
required:"未选择文件"
},
mp_operator_phone:{
mobile:"请输入正确的手机号码"
},
mp_operator_tel:"帐号运营者座机不能为空",
mp_operator_email:{
required:"请输入正确的邮箱格式",
trimemail:"请输入正确的邮箱格式"
},
business_license_stuff:{
required:"企业工商营业执照不能为空"
},
application_letter:{
required:"未选择文件"
},
mp_operator_idcard_stuff:{
required:"未选择文件"
},
soso_map_pos:{
required:"SOSO地图坐标URL不能为空"
},
office_address:{
required:"机构地址不能为空"
},
registered_address:{
required:"注册地址不能为空"
},
office_phone:{
required:"办公电话不能为空"
},
organization_code_stuff:{
required:"组织机构代码证不能为空"
},
scale:{
required:"请输入企业规模",
number:"企业规模必须是数字，请输入正确的数字格式"
},
extra_scale:{
required:"请输入上下游成员规模",
number:"上下游成员必须是数字，请输入正确的数字格式"
},
social_insure_scale_stuff:{
required:"请至少上传一个证明"
},
relation_proof_stuff:{
required:"未选择文件"
},
partner_scale_proof_stuff:{
required:"未选择文件"
}
},
errorPlacement:function(e,r){
var i=r.parent().parent();
i.find(".fail").remove(),e.insertBefore(1==r.attr("scale_proof")?r.is(".file_field")?i.find("#wages_paying_scale_stuff_preview"):i.find(".name_example"):r.is(".file_field")?i.find(".upload_preview"):i.find(".frm_tips"));
},
ignore:[],
commonMsgs:u,
telephoneFilter:a,
submitHandler:function(e){
function r(){
t.post({
url:"/acct/wxverify?action="+i,
data:u,
timeout:6e4,
error:function(){
$("#submit_info").btn(!0);
}
},function(e){
if("0"!=e.base_resp.ret)return"10306"==e.base_resp.ret||("202100"==e.base_resp.ret?wx.cgiData.checkAdminPopup.load():"210001"==e.base_resp.ret?(d.err("该组织机构代码已被认证，请重新填写。"),
$("#organization_code").focus()):t.show(e)),void $("#submit_info").btn(!0);
n.remove(_),n.remove(s);
var r=location.href;
l&&2==l?location.href=wx.url("/merchant/order?action=detail&t=service/detail&order_id="+wx.cgiData.order_id):(-1==location.search.indexOf("&step=")&&(r+="&step=naming"),
location.href=c.replace(r,"step","naming"));
}),$("#submit_info").btn(!1);
}
var i,u=a(e),l=wx.cgiData.refill_type;
u.refill_type=l,""==u.extra_scale&&(u.extra_scale=0),u.step=wx.cgiData.step,i=l?"submit_refill":"submit_info",
console.log(u),document.activeElement&&"INPUT"===document.activeElement.tagName&&document.activeElement.blur(),
l&&2==l?o.show({
type:"warn",
mask:!0,
msg:"确定提交？|一旦提交，你将消耗一次重填的机会。",
buttons:[{
text:"确定",
click:function(){
var e=this;
r(),e.hide();
}
},{
text:"取消",
type:"normal",
click:function(){
this.hide();
}
}]
}):r();
},
invalidHandler:function(e,r){
var i=r.errorList[0];
if(i&&$(i.element).is("input[type=hidden]")){
{
var a=$(i.element),t=a.parent(),o=t.offset().top-$(window).height()/2,n=$(window).scrollLeft();
$(window).scrollTop();
}
window.scrollTo(n,o);
}
}
};
});