define("shop/config.js",[],function(g,i,o){
"use strict";
o.exports={
defaultData:{
header:{
name:"小店招牌",
color:"red"
},
tmpl1:{
group_name:"分组名称",
group_id:"",
product_list:[{
base_attr:{
img_info:["/mpres/htmledition/images/shop/bg_goods_img_default.png"],
ori_price:200,
name:"商品名称"
},
price:100
},{
base_attr:{
img_info:["/mpres/htmledition/images/shop/bg_goods_img_default.png"],
ori_price:200,
name:"商品名称"
},
price:100
},{
base_attr:{
img_info:["/mpres/htmledition/images/shop/bg_goods_img_default.png"],
ori_price:200,
name:"商品名称"
},
price:100
},{
base_attr:{
img_info:["/mpres/htmledition/images/shop/bg_goods_img_default.png"],
ori_price:200,
name:"商品名称"
},
price:100
}]
},
tmpl2:{
groups:[{
group_name:"分组一",
group_id:""
},{
group_name:"分组二",
group_id:""
},{
group_name:"分组三",
group_id:""
},{
group_name:"分组四",
group_id:""
}]
},
tmpl3:{
img:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
group_id:""
},
tmpl4:{
groups:[{
img:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
group_id:""
},{
img:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
group_id:""
},{
img:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
group_id:""
}]
},
tmpl5:{
img_background:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
groups:[{
group_name:"分组一",
group_id:""
},{
group_name:"分组二",
group_id:""
},{
group_name:"分组三",
group_id:""
},{
group_name:"分组四",
group_id:""
}]
},
tmpl7:{},
tmpl11:{
groups:[{
group_name:"分组一",
group_id:""
},{
group_name:"分组二",
group_id:""
},{
group_name:"分组三",
group_id:""
},{
group_name:"分组四",
group_id:""
}],
group_all:!1
},
tmpl12:{
img:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
card_id:""
},
tmpl13:{
groups:[{
img:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
card_id:""
},{
img:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
card_id:""
},{
img:"/mpres/htmledition/images/shop/bg_goods_img_default.png",
card_id:""
}]
}
}
};
});