define("common/wx/mpEditor/editor_config.js",[],function(){
"use strict";
var e=window.wx.data.lang,i=window.wx.data.t,t=window.UEDITOR_HOME_URL=/^dev/.test(location.host)?"/mpres/htmledition/ueditor/":"//res.wx.qq.com/mpres/htmledition/ueditor/";
window.UEDITOR_CONFIG={
UEDITOR_HOME_URL:t,
imageUrl:"/cgi-bin/uploadimg2cdn?t=ajax-editor-upload-img&lang="+e+"&token="+i,
imagePath:"",
compressSide:1,
scrawlUrl:t+"php/scrawlUp.php",
scrawlPath:t+"php/",
fileUrl:t+"php/fileUp.php",
filePath:t+"php/",
catchRemoteImageEnable:!0,
catcherUrl:"/cgi-bin/uploadimg2cdn?lang="+e+"&token="+i,
catcherPath:t+"php/",
catchFieldName:"imgurl",
separater:"",
imageManagerUrl:t+"php/imageManager.php",
imageManagerPath:t+"php/",
snapscreenHost:"127.0.0.1",
snapscreenServerUrl:t+"php/imageUp.php",
snapscreenPath:t+"php/",
wordImageUrl:t+"php/imageUp.php",
wordImagePath:t+"php/",
getMovieUrl:t+"php/getMovie.php",
toolbars:[["more","|","fontsize","|","blockquote","horizontal","|","removeformat","link","unlink","|","insertvideo2","insertimage","insertvote","insertmusic","insertaudio","insertcard"],["bold","italic","underline","forecolor","backcolor","|","justifyleft","justifycenter","justifyright","|","rowspacingtop","rowspacingbottom","lineheight","|","insertorderedlist","insertunorderedlist","|","imagenone","imageleft","imageright","imagecenter"]],
toolbarsPermission:{
more:1
},
labelMap:{
anchor:"",
undo:""
},
webAppKey:"",
lang:e,
theme:"default",
customDomain:!0,
initialFrameWidth:"auto",
autoHeightEnabled:!1,
sourceEditor:"textarea"
};
});