define("wifi/homepage_edit.js",["wifi/top.js","biz_web/ui/checkbox.js","common/wx/Cgi.js","common/wx/Tips.js","biz_web/utils/upload.js"],function(t){
"use strict";
t("wifi/top.js"),t("biz_web/ui/checkbox.js");
var e=t("common/wx/Cgi.js"),i=t("common/wx/Tips.js"),a=t("biz_web/utils/upload.js"),s={
$jsWelcomeView:$(".js_view_welcome"),
$jsWelcomeText:$(".js_welcome_text"),
$jsEdit:$(".js_edit"),
$jsEditView:$(".js_edit_view"),
$jsLogoView:$(".js_logo_view"),
$jsNameView:$(".js_name_view"),
$jsDescView:$(".js_desc_view"),
$jsWelcomeCheckbox:$(".js_welcome_checkbox"),
$jsUploadBtn:$("#js_upload_btn"),
$jsUrl:$(".js_url"),
$jsName:$(".js_name"),
$jsDesc:$(".js_desc"),
$jsTmplCheckbox:$(".js_tmpl_checkbox"),
$jsSubmit:$("#js_submit"),
$jsBuileQrcode:$(".js_build_qrcode"),
$jsQrcodeView:$(".js_qrcode_view"),
$jsUrlError:$("#js_url_error")
},o={
data:{},
init:function(){
this.setData(wx.cgiData),1!=o.getData().ad_template&&2!=o.getData().ad_template&&o.setData({
ad_template:"2"
});
},
setData:function(t){
for(var e in t)t.hasOwnProperty(e)&&(this.data[e]=t[e]);
},
getData:function(){
return this.data;
},
valid:function(){
return 1==this.data.ad_template?this.data.custom_url?!0:(s.$jsUrl.focus(),i.err("自定义链接不能为空"),
!1):2==this.data.ad_template?this.data.content_logo?this.data.content_name?this.data.content_name.length>14?(i.err("品牌名称不能多于14个字符"),
s.$jsName.focus(),!1):this.data.content_desc?this.data.content_desc.length>30?(i.err("品牌宣传语不能多于30个字符"),
s.$jsDesc.focus(),!1):!0:(i.err("请输入品牌宣传语"),s.$jsDesc.focus(),!1):(i.err("请输入品牌名称"),
s.$jsName.focus(),!1):(i.err("请上传logo"),!1):!1;
}
},n={
_hasInitCustomEdit:!1,
_hasInitBaseEdit:!1,
_decodeData:function(t){
var e=document.createElement("div");
return $(e).html(t),$(e).text();
},
_welcomeText:{
0:s.$jsWelcomeText.eq(0).text(),
1:s.$jsWelcomeText.eq(1).text(),
2:s.$jsWelcomeText.eq(2).text(),
3:s.$jsWelcomeText.eq(3).text()
},
_initCustomEdit:function(){
n._hasInitCustomEdit||(c.initCustomEdit(),s.$jsUrl.val(n._decodeData(o.getData().custom_url)),
n._hasInitCustomEdit=!0);
},
_initBaseEdit:function(){
n._hasInitBaseEdit||(c.initBaseEdit(),s.$jsLogoView.attr("src",o.getData().content_logo),
s.$jsName.val(o.getData().content_name),s.$jsNameView.text(o.getData().content_name||"品牌名称"),
s.$jsDesc.val(o.getData().content_desc),s.$jsDescView.text(o.getData().content_desc||"此处展示宣传语"),
n._hasInitBaseEdit=!0);
},
init:function(){
n.setWelcomeContent(o.data.bar_type),n.setAdTemplate(o.data.ad_template);
},
setWelcomeContent:function(t){
""==t&&(t=0),s.$jsWelcomeView.text(n._welcomeText[t]);
},
setAdTemplate:function(t){
1!=t&&2!=t&&(t=2),1==t?(s.$jsEdit.eq(0).show(),s.$jsEdit.eq(1).hide(),s.$jsEditView.eq(0).show(),
s.$jsEditView.eq(1).hide(),n._initCustomEdit()):2==t&&(s.$jsEdit.eq(0).hide(),s.$jsEdit.eq(1).show(),
s.$jsEditView.eq(0).hide(),s.$jsEditView.eq(1).show(),n._initBaseEdit());
}
},c={
_initWelcomEdit:function(){
s.$jsWelcomeCheckbox.checkbox({
multi:!1,
onChanged:function(t){
n.setWelcomeContent(t.data("type")),o.setData({
bar_type:t.data("type")
});
}
}).adjust(o.data.bar_type||"0");
},
_initBarTypeEdit:function(){
s.$jsTmplCheckbox.checkbox({
multi:!1,
onChanged:function(t){
n.setAdTemplate(t.data("type")),o.setData({
ad_template:t.data("type")
});
}
}).adjust(o.data.ad_template||"2");
},
initBaseEdit:function(){
a.uploadCdnFile({
container:s.$jsUploadBtn,
multi:!1,
accept:{
extensions:"bmp,jpeg,jpg",
mimeTypes:"image/*"
},
fileSingleSizeLimit:2097152,
onComplete:function(t,e,a,n){
n&&n.base_resp&&0==n.base_resp.ret?(s.$jsLogoView.attr("src",n.content),o.setData({
content_logo:n.content
})):i.err("系统错误");
}
}),s.$jsName.on("input propertychange",function(){
s.$jsNameView.text($(this).val()?$(this).val():"品牌名称"),o.setData({
content_name:$(this).val()
});
}),s.$jsDesc.on("input propertychange",function(){
s.$jsDescView.text($(this).val()?$(this).val():"此处展示宣传语"),o.setData({
content_desc:$(this).val()
});
});
},
initCustomEdit:function(){
s.$jsBuileQrcode.on("click",function(){
var t=s.$jsUrl.val();
return/^http(s)?:\/\//.test(t)&&""!=t?void s.$jsQrcodeView.attr("src",wx.url("/wifi/wifimpcomm?action=get_qr_img&url="+window.encodeURIComponent(s.$jsUrl.val()))):(s.$jsUrlError.show(),
s.$jsUrl.focus(),!1);
}),s.$jsUrl.on("input propertychange",function(){
s.$jsUrlError.hide(),o.setData({
custom_url:$(this).val()
});
});
},
init:function(){
c._initWelcomEdit(),c._initBarTypeEdit();
}
},d=function(){
o.init(),n.init(),c.init(),s.$jsSubmit.on("click",function(){
if(o.valid()){
var t={
shop_id:o.getData().shop_id,
bar_type:o.getData().bar_type,
content_logo:o.getData().content_logo,
content_name:o.getData().content_name,
content_desc:o.getData().content_desc,
custom_url:o.getData().custom_url,
ad_template:o.getData().ad_template
};
e.post({
url:wx.url("/wifi/wifihomepage?action=edit_ori_store_info"),
data:t
},function(t){
t&&t.base_resp&&0==t.base_resp.ret&&(i.suc("提交成功"),location.href=wx.url("/wifi/wifihomepage?t=wifi/homepage_list_tmpl&action=get_ori_store_info_list&page_idx=1&page_size=10"));
});
}
});
};
d();
});