define("media/media_cgi.js",["media/common.js","common/wx/Tips.js","common/wx/Cgi.js","resp_types/base_resp.rt.js","resp_types/file_cnt.rt.js"],function(e){
"use strict";
var r=e("media/common.js"),s=e("common/wx/Tips.js"),t=e("common/wx/Cgi.js"),i=e("resp_types/base_resp.rt.js"),n=e("resp_types/file_cnt.rt.js"),a={
del:function(e,r){
t.post({
mask:!1,
url:wx.url("/cgi-bin/operate_appmsg?sub=del&t=ajax-response"),
data:{
AppMsgId:e
},
rtDesc:i,
error:function(){
s.err("删除失败");
}
},function(e){
"0"==e.ret?(s.suc("删除成功"),r&&r(e)):s.err("删除失败");
});
},
del_sv:function(e,r){
t.post({
mask:!1,
url:wx.url("/cgi-bin/modifyfile?oper=del&t=ajax-response"),
data:{
fileid:e
},
rtDesc:i,
error:function(){
s.err("删除失败");
}
},function(e){
e.base_resp&&0==+e.base_resp.ret?(s.suc("删除成功"),r.suc&&r.suc(e)):(s.err("删除失败"),
r.fail&&r.fail(e));
});
},
edit_sv:function(e,r){
t.post({
mask:!1,
url:wx.url("/cgi-bin/modifyfile?oper=rename&t=ajax-response"),
data:{
fileid:e.id,
filename:e.name
},
rtDesc:i,
error:function(){
s.err("编辑失败");
}
},function(e){
e.base_resp&&0==+e.base_resp.ret?(s.suc("编辑成功"),r.suc&&r.suc(e)):(s.err("编辑失败"),
r.fail&&r.fail(e));
});
},
save:function(e,i,n,a,o,p){
var c=wx.url(n.AppMsgId?"/cgi-bin/operate_appmsg?t=ajax-response&sub=update&type=%s".sprintf(i):"/cgi-bin/operate_appmsg?t=ajax-response&sub=create&type=%s".sprintf(i));
n.ajax=1,t.post({
url:c,
data:n,
dataType:"json",
rtDesc:{
ret_R:"string",
appMsgId_R:"number"
},
error:function(e,r){
"timeout"!=r&&s.err("保存失败"),o&&o(!1,-1,"",{
myErrMsg:"保存失败"
});
},
complete:p
},function(e){
if("0"==e.ret)s.suc("保存成功"),a&&a(e);else{
var t=r.articleRetCode(e),i=t.index;
e.myErrMsg=t.errmsg,o&&o(i,e.ret,e.remind_wording,e);
}
});
},
preview:function(e,i,n,a,o){
t.post({
url:wx.url("/cgi-bin/operate_appmsg?sub=preview&t=ajax-appmsg-preview&type=%s".sprintf(i)),
data:n,
dataType:"json",
rtDesc:{
ret_R:"string"
},
error:function(){
s.err("发送失败，请稍后重试"),o&&o({
word:"发送失败，请稍后重试"
});
}
},function(e){
if("0"==e.ret)s.suc("发送预览成功，请留意你的手机微信"),a&&a(e);else{
var t=r.articleRetCode(e);
e.word=t.errmsg,e.antispam=t.index,15==i&&s.err(e.word),o&&o(e);
}
});
},
modifyPreview:function(e,i,n){
t.post({
url:wx.url("/cgi-bin/masssendmodify?action=preview"),
data:e,
dataType:"json",
rtDesc:{
ret_R:"string"
},
error:function(){
s.err("发送失败，请稍后重试"),n&&n({
word:"发送失败，请稍后重试"
});
}
},function(e){
if("0"==e.ret)s.suc("发送预览成功，请留意你的手机微信"),i&&i(e);else{
var t=r.articleRetCode(e);
e.word=t.errmsg,e.antispam=t.index,15==type&&s.err(e.word),n&&n(e);
}
});
},
getList:function(e,r,a,o,p,c){
var u="";
u=wx.url(p?"/cgi-bin/appmsg?type=%s&action=list&begin=%s&count=%s&query=%s&f=json".sprintf(e,r,a,p):"/cgi-bin/appmsg?type=%s&action=list&begin=%s&count=%s&f=json".sprintf(e,r,a)),
0==c?u=wx.url("/cgi-bin/appmsg?type=%s&action=list&begin=%s&count=%s&f=json".sprintf(e,r,a)):1==c&&(u=wx.url("/cgi-bin/video_mgr?type=%s&action=get_video_list&begin=%s&offset=%s&f=json".sprintf(e,r,a))),
t.get({
mask:!1,
url:u,
rtDesc:$.extend({},i,{
app_msg_info:$.extend({},n,{
item_R:[],
search_cnt:"number"
})
}),
error:function(){
s.err("获取列表失败");
}
},function(e){
e&&e.base_resp&&0==e.base_resp.ret?o&&o(e.app_msg_info):s.err("获取列表失败");
});
},
getSingleList:function(e,r,i,n){
t.get({
mask:!1,
url:wx.url("/cgi-bin/appmsg?type=%s&action=for_advert&begin=%s&count=%s&f=json".sprintf(e,r,i)),
error:function(){
s.err("获取列表失败");
}
},function(e){
e&&e.base_resp&&0==e.base_resp.ret?n&&n(e.app_msg_info):s.err("获取列表失败");
});
}
},o={
save:function(e,r,i){
var n=wx.url("/cgi-bin/operate_vote");
e.ajax=1,t.post({
url:n,
data:e,
error:function(){
s.err("保存失败"),i&&i();
}
},function(e){
e&&e.base_resp&&0==e.base_resp.ret?(s.suc("保存成功"),r&&r(e)):(s.err("保存失败"),i&&i(e));
});
}
};
return{
rename:function(e,r,i){
t.post({
mask:!1,
url:wx.url("/cgi-bin/modifyfile?oper=rename&t=ajax-response"),
data:{
fileid:e,
fileName:r
},
error:function(){
s.err("重命名失败");
}
},function(e){
if(!e||!e.base_resp)return void s.err("重命名失败");
var r=e.base_resp.ret;
if("0"==r)s.suc("重命名成功"),i&&i(e);else switch(r){
case"200002":
s.err("素材名不能包含空格");
break;

default:
s.err("重命名失败");
}
});
},
del:function(e,r){
t.post({
mask:!1,
url:wx.url("/cgi-bin/modifyfile?oper=del&t=ajax-response"),
data:{
fileid:e
},
error:function(){
s.err("删除失败");
}
},function(e){
if(!e||!e.base_resp)return void s.err("删除失败");
var t=e.base_resp.ret;
"0"==t?(s.suc("删除成功"),r&&r(e)):s.err("删除失败");
});
},
getList:function(e,r,a,o){
(2==e||3==e)&&(e+="&action=select"),t.get({
mask:!1,
url:wx.url("/cgi-bin/filepage?type=%s&begin=%s&count=%s&f=json".sprintf(e,r,a)),
rtDesc:$.extend({},i,{
page_info_R:$.extend({},n,{
file_item_R:[{
file_id_R:"number",
name_R:"string",
size_R:"string",
update_time_R:"number",
type_R:"number"
}]
})
}),
error:function(){
s.err("获取列表失败");
}
},function(e){
e&&e.base_resp&&0==e.base_resp.ret?o&&o(e.page_info):s.err("获取列表失败");
});
},
appmsg:a,
vote:o
};
});