define("ad_system/pop_test.js",["common/wx/Cgi.js","common/wx/Tips.js","common/wx/dialog.js","common/wx/popup.js"],function(a){
"use strict";
a("common/wx/Cgi.js"),a("common/wx/Tips.js"),a("common/wx/dialog.js");
a("common/wx/popup.js"),$("#popTpl").popup({
title:"添加广告主黑名单",
className:"lists_pop",
width:960,
buttons:[{
text:"添加黑名单",
click:function(){},
type:"disabled"
},{
text:"取消",
click:function(){
this.remove();
}
}],
close:function(){
this.remove();
}
}),$("#popList").append(tpl.render("tpl",{
list:[{
alias:"gh_5dd066b5a669",
nick_name:"sy",
icon:""
},{
alias:"style10010",
nick_name:"sy",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM5uHPmcibqeOWZOtMRbZZ5LWyFh9UbSiclPTq7HUDEeZrmg"
},{
alias:"hzsysj",
nick_name:"sy",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM6JqibhBkiaWC39PPzhwnFqNNzKrichbB1ibwvlA7UtzvDDuw"
},{
alias:"gh_f131703f9a31",
nick_name:"sy",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM6u1ibXT7tCf9rZUZhRaCicAOhTfo9Fg6ibUyXniaxoz140DQ"
},{
alias:"sysy1992210",
nick_name:"sy",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM6hluXvicPgHTVnFT2d49daBKECZOXzibpPmaN6da7oU10Q"
},{
alias:"gh_9608d9353322",
nick_name:"sy",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM5mkn9vIx9u6VkrLfMYzRKsS1ZJ6ysugcJsJMaWH8RyrA"
},{
alias:"gh_527c1d47b638",
nick_name:"sy油画艺术",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM5eqs6WVcd667rTe2YTzf4liaVsVWx3BF4tlibho7beZXzw"
},{
alias:"gh_43fb9728ddea",
nick_name:"sy深蓝物业",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM6IvQyZYdGMJ9tbSiaJN5BN6efAiaIH3AAYPpdTBsHlMgsg"
},{
alias:"summercake_ng",
nick_name:"sy烘焙",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM5PHz9jfEPG94cLNJHTEqShXKMplWQlyEDrR3A9WVsoVw"
},{
alias:"wuyuehuajiuba",
nick_name:"sy五月花酒吧",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM50bnsKOfEAJxFKc57DztKSqMRzGJibTQiamRpxRam2q5fA"
},{
alias:"yinger_72",
nick_name:"HR影儿sy",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM6XZ4bV9xCeeyTxpic6GS8KgJH6KuDmrUiarJUGybdpXH1Q"
},{
alias:"Q45168",
nick_name:"sy刘杨",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM7ULcfJJS86w67kTTwXRQghh6bD7HAKupiaSKGIichs7icWQ"
},{
alias:"gh_d371a97aa831",
nick_name:"sy小淘气",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM5r2wOicmlz8VD5MK73CvgKbalY9iaQfXAy3wp3QkAGvtFQ"
},{
alias:"SY-fengming",
nick_name:"sy-冯明",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM4OU6eznFf3bdRPfNEkWxVFXtmNYRmTFwKYy4OOkeUvyQ"
},{
alias:"syjingpin",
nick_name:"sy精品",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM6tYHy1eFv4WqutVm02SXIoaVoG1UmLAMoQchIRVVqQbg"
},{
alias:"sy-GD777",
nick_name:"sy三友手机配件",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM75sdekUPjyCNsMy3DG6UibYaDicXks6leMkn9aMUMU0gHg"
},{
alias:"gh_f767a5eb0983",
nick_name:"sy美丽工程",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM6H5HxxBh5bFLttzZbCA8mEscRicwpY1eu8LYeHenwPVJA"
},{
alias:"jiesezhushou",
nick_name:"全能戒sy助手",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM5jozA0gl0bfQ2gL5gibhnpjcCIWiaydLYJmQFuicxumKGYA"
},{
alias:"zw520sy",
nick_name:"张伟sy",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM7goO7bTmq5Xcqdhx0Uy6HSdU5HCjIDCv2zHwCdWJtORg"
},{
alias:"uucare-sy",
nick_name:"优月季-sy",
icon:"http://wx.qlogo.cn/mmhead/Q3auHgzwzM5SdtiabNHrKv4SIdUfr9GicoxlvDJ7qnjFsXttohWuH1QA"
}]
}));
});