define("wxverify/shopreg.js",["common/wx/Cgi.js","wxverify/commonreg.js"],function(e,r,n){
"use strict";
function i(){
$("#shopreg").validate($.extend(!0,{},o,{
rules:{
parent_company:"required",
official_website:"required",
registered_capital:"required",
registered_address:"required",
generic_business_type:{
required:!0,
maxlength:1e3
},
front_business_type:{
required:!0,
maxlength:1e3
},
online_store_proof_stuff:"required",
organization_code:"required",
organization_code_stuff:"required",
online_store_name:"required",
online_store_product_url:"required"
},
messages:{
name:"企业全称不能为空",
parent_company:"隶属企业不能为空",
official_website:"网店地址不能为空",
registered_capital:"注册资本金不能为空",
registered_address:"企业注册地址不能为空",
generic_business_type:{
required:"一般经营范围不能为空",
maxlength:"一般经营范围不超过1000字"
},
front_business_type:{
required:"前置许可经营范围不能为空",
maxlength:"前置许可经营范围不能超过1000字"
},
online_store_proof_stuff:"网店店铺管理后台截屏不能为空",
office_address:"企业办公地址不能为空",
legal_person:"法定代表人/企业负责人姓名不能为空",
account_name:"企业开户名称不能为空",
bank_name:"企业开户银行不能为空",
bank_account:"企业对公银行账号不能为空",
online_store_name:"网店名称不能为空",
online_store_product_url:"验证网店所有权的商品URL不能为空"
}
}));
}
{
var o=(e("common/wx/Cgi.js"),e("wxverify/commonreg.js"));
o.commonMsgs;
}
n.exports=function(){
i();
};
});